### ISSUE TITLE
[wok] autogen.sh --system gives No names found message

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/wok#1]
[chandra@localhost wok]$ ./autogen.sh --system
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
configure: loading site script /usr/share/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for a Python interpreter with version >= 2.6... python
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python2.7/site-packages
checking for pep8... /usr/bin/pep8
checking python module: unittest... yes
checking python module: cython... yes
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... none
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for ld used by GCC... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for cheetah... /usr/bin/cheetah
checking for pyflakes... no
configure: WARNING: pyflakes not found
checking for sassc... /usr/bin/sassc
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating po/Makefile.in
config.status: creating po/gen-pot
config.status: creating Makefile
config.status: creating docs/Makefile
config.status: creating docs/wokd.8
config.status: creating src/Makefile
config.status: creating src/nginx/Makefile
config.status: creating src/wok/Makefile
config.status: creating src/wok/control/Makefile
config.status: creating src/wok/model/Makefile
config.status: creating src/wok/xmlutils/Makefile
config.status: creating src/wok/plugins/Makefile
config.status: creating src/wok/plugins/sample/Makefile
config.status: creating src/wok/plugins/sample/po/Makefile.in
config.status: creating src/wok/plugins/sample/sample.conf
config.status: creating src/wok/plugins/sample/ui/Makefile
config.status: creating src/wok/plugins/sample/ui/config/Makefile
config.status: creating src/wok/plugins/sample/ui/js/Makefile
config.status: creating src/wok/plugins/sample/ui/pages/Makefile
config.status: creating ui/Makefile
config.status: creating ui/base64/Makefile
config.status: creating ui/css/Makefile
config.status: creating ui/css/fontawesome/Makefile
config.status: creating ui/css/opensans/Makefile
config.status: creating ui/images/Makefile
config.status: creating ui/images/theme-default/Makefile
config.status: creating ui/js/Makefile
config.status: creating ui/libs/Makefile
config.status: creating ui/libs/bootstrap/Makefile
config.status: creating ui/libs/bootstrap-select/Makefile
config.status: creating ui/libs/bootstrap-select/dist/Makefile
config.status: creating ui/libs/bootstrap-select/dist/js/Makefile
config.status: creating ui/libs/bootstrap-select/dist/css/Makefile
config.status: creating ui/libs/es5-shim/Makefile
config.status: creating ui/libs/jquery/Makefile
config.status: creating ui/libs/jquery-i18n/Makefile
config.status: creating ui/libs/jquery-ui/Makefile
config.status: creating ui/libs/jquery-ui/themes/Makefile
config.status: creating ui/libs/jquery-ui/themes/base/Makefile
config.status: creating ui/libs/jquery-ui/themes/base/images/Makefile
config.status: creating ui/pages/Makefile
config.status: creating ui/pages/websockify/Makefile
config.status: creating contrib/Makefile
config.status: creating contrib/DEBIAN/Makefile
config.status: creating contrib/DEBIAN/control
config.status: creating contrib/wok.spec.fedora
config.status: creating contrib/wok.spec.suse
config.status: creating tests/Makefile
config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: creating src/wok/plugins/sample/po/POTFILES
config.status: creating src/wok/plugins/sample/po/Makefile
config.status: executing depfiles commands

I guess this due to tags ; git describe --tags

**Comment by pvital** [comment]
@chandrureddy what is your distro?

**Comment by pvital** [comment]
Ok, this is happening because the new Wok repository doesn't have any tag committed. To fix this issue locally you can run something like the following command:

```
$ git tag -a 1.5.1 -m "Wok 1.5.1 - development release."
```

To solve this issue to every one, it's necessary to push a tag to Github repository. @alinefm can you do this?

**Comment by chandrureddy** [comment]
This issue has to resolved for gingerbase and gingers390x as well.

**Comment by chandrureddy** [comment]
Aline,

Looks like still we have tag issue.
@alinefm , Can you push tag to Github repository ?


Regards
Chandra
