### ISSUE TITLE
In runcommand, enabling UTF-8 characters support in command ouput

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/wok#101]
In runcommand, LC_ALL set to C which overrides all LC_* values to default even if it is present in os environment variable, this result to have Lang set to always en_US even if it is set as different in os environment.

For e.g, if I have Lang as en_US.UTF-8, as I know when my system command can have stdout or stderr will have UTF-8 non-ascii characters. In this case have LC_ALL = C will result then Lang to en_US only and the non-ascii will replace with "?".

For e.g if I have interface name with té12 and if up is failing, the stderr we got with current upstream code is:

GINNET0016E: Unable to activate the interface on 'té12', 'Could not load file '/etc/sysconfig/network-scripts/ifcfg-t?12'
Could not load file '/etc/sysconfig/network-scripts/ifcfg-t?12'
Could not load file '/etc/sysconfig/network-scripts/ifcfg-t?12'
./network-functions: line 518: echo: write error: Operation not permitted
./network-functions: line 518: echo: write error: Operation not permitted
Error: Connection activation failed: No compatible connection found for master device t?12.

However it should be,
GINNET0016E: Unable to activate the interface on 'té12', 'Could not load file '/etc/sysconfig/network-scripts/ifcfg-té12'
Could not load file '/etc/sysconfig/network-scripts/ifcfg-té12'
Could not load file '/etc/sysconfig/network-scripts/ifcfg-té12'
./network-functions: line 518: echo: write error: Operation not permitted
./network-functions: line 518: echo: write error: Operation not permitted
Error: Connection activation failed: No compatible connection found for master device té12.

So LC_ALL should only be set to C if os env variable is not has any value for Lang. Please let me know  views on this.

**Comment by danielhb** [comment]
On 04/14/2016 01:43 AM, Archana Singh wrote:
>
> In runcommand, LC_ALL set to C which overrides all LC_* values to 
> default even if it is present in os environment variable, this result 
> to have Lang set to always en_US even if it is set as different in os 
> environment.
>
> For e.g, if I have Lang as en_US.UTF-8, as I know when my system 
> command can have stdout or stderr will have UTF-8 non-ascii 
> characters. In this case have LC_ALL = C will result then Lang to 
> en_US only and the non-ascii will replace with "?".
>

I was the one that did this change in run_command due to problems in how 
programs were being parsed in different languages (lscpu for example).

Now, I wasn't aware of this side effect. I had no intentions of setting 
the charset to ASCII. As long as the program outputs in English I don't 
see any problems with the charset being UTF8.

We need a way to guarantee that the program output will be English but 
not messing with the charset. In fact, we might even force UTF-8 ....

**Comment by archu-s** [comment]
Ya, that is true, output needs to be in English, but I guess charset should be UTF-8. What do you think about setting LC_ALL to en_US.UTF-8 instead of C?

**Comment by danielhb** [comment]
I didn't have the time to research it yet, but if 'en_US.UTF-8' is a valid value for the LC_ALL variable to always provide English output to the command line tools and at the same time allows UTF-8 charset, I agree.
