### ISSUE TITLE
Wok Activity log does not show time zone, which gives wrong info if timezone is changed.

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/wok#102]
Currently activity log does not show the time zone of the log timings.

So for e.g if user login at 18:55 CST with CSt as timezone on system, and after which is timezone on system is changed to IST, still the actitivy log shows the login time as 18:55 which is not correct as per changed time zone. It should either say 18:55 CST or 5:25 IST(the converted value) with correct date.

So the date time should have timezone in the log file and activity log in UI.

**Comment by alinefm** [comment]
Hi @archu-s 

The log entry is generated on sever side, ie, the time zone used for it will be the server time zone. So it will not change according to client side changes.
If you think it is important to have the timezone displayed, I am OK with that, but keep in mind it will be the same across all logs entries and will not be changed according to client timezone.
(I have commented the same on #100)

**Comment by archu-s** [comment]
ya, I agree.

**Comment by lcorreia** [comment]
I will handle this as part of issue #100 . We can close this.

**Comment by alinefm** [comment]
Closing based on last comment.
