### ISSUE TITLE
logging of datetime in ISO format along with timezone in *.log.

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/wok#105]
Currently all the .log does not have datetime as per ISO format and also it does not have the timezone of the system.

ISO datetime format is the standard format to be followed as per globalization standards for logging purpose.
Coming to datetime zone logged in log file, either we should have able to log it or should have API to give the system timezone. Not sure which is the best approach. 

Looking for inputs on these aspects.

**Comment by lcorreia** [comment]
Hi, the best approach in my opinion is to write to the log file using the correct datetime format.

Regarding APIs, the request logger reads from the wok-request.log* files, so we may need to adjust the code to recognize the new datetime format if changed.

**Comment by alinefm** [comment]
Hi @archu-s and @lcorreia 

The log files are generated by logrotate so we want to change the log file name we need to check any logrotate configuration to change that.
But I am wondering if it is really needed as the file is created in the server side, it is will have the datime format according to the server timezone.

**Comment by archu-s** [comment]
@Aline: That is true, my point here is in addition to datetime in log file, it should also have the timezone of server in the log file.

**Comment by lcorreia** [comment]
The idea is not to change file name. Just fix timestamp format in file contents.
I will handle it as part of issue #100 . We can close this.

**Comment by alinefm** [comment]
Hi @lcorreia 

#100 is not related to the file name format. But it is related to the information provided by the user log feature. So I prefer to keep this open to track the file name update as requested.

**Comment by lcorreia** [comment]
Since that file does not work as a .log file anymore (it's a .data now, moved to /data dir, working as a log entry database), I believe we don't need to fix this anymore.
