### ISSUE TITLE
Asynchronous notifications are not persistent on UI

### ISSUE THREAD

**Issue by pvital** [kimchi-project/wok#109]
When an asynchronous notification is added (by backend add_notification() method) the notification box is displayed on the screen, however if user change to a different tab (or sub-tab) without click on the X button of the notification box, the notification disappears.

The notification box should be visible in any tab, even if user change to a different tab, until user click on X button of the notification box.

**Comment by samhenri** [comment]
I think we could use localStorage or sessionStorage for this. In this specific scenario we don't have to worry about the user going to an anonymous or private tab because once he logs again on the first tab it loads it would get the notifications again from the back-end.

**Comment by alinefm** [comment]
Fixed by ea220acd67954aacdbfdbeb5eefeed7be31b092a
