### ISSUE TITLE
Multi language support required for tabs

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/wok#11]
Multi language support required for tabs.

For example Host tab or the new tabs introduced for Ginger base (Dashboard, Update etc...)

![screen shot 2015-12-17 at 6 33 06 pm](https://cloud.githubusercontent.com/assets/10830725/11870327/b437636a-a4ec-11e5-8b39-2e4d0fa637aa.png)

Right now they are in English. not sure if this issue has to be moved to plugins but I guess we need to support !!!

**Comment by alinefm** [comment]
In fact it is an issue on Ginger Base side. It was already fixed by https://github.com/kimchi-project/gingerbase/commits/ebe9cbb6d8e1a2af98667600eb3c191a4a37e251
