### ISSUE TITLE
WebVNC (View Console) wrong keymap 

### ISSUE THREAD

**Issue by tavoc** [kimchi-project/wok#113]
**Version:**   
WOK/Gingerbase/Kimchi 2.1.0-0

**Issue:** 
In Kimchi Guest Tab you can select "view console" and get an WebVNC Session to your guest.
In this enviroment an english keyboard layout is used.

I am using german in all my guests and therefore have a "qwertz" instead of "qwerty" layout. Whenever you are using special characters it is inconvenient.

**Suggestion:** 
Use the keyboad layout of the host system. Or please add a possibility to change the keyboard layout for all guests or a setting for specific guests.

**Comment by danielhb** [comment]
@tavoc , this bug is already opened in Kimchi:

https://github.com/kimchi-project/kimchi/issues/411

Feel free to join the discussion there. I have updates about it myself and will update it now.

Thanks!

**Comment by alinefm** [comment]
Closing it as duplicated of kimchi-project/kimchi#411
