### ISSUE TITLE
logrotate fails

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/wok#118]
[suresh@localhost ~]$ sudo logrotate /etc/logrotate.conf 
error: wokd.in:1 lines must begin with a keyword or a filename (possibly in double quotes)
error: wokd.in:8 unexpected }
error: found error in file wokd.in, skipping
[suresh@localhost ~]$

**Comment by alinefm** [comment]
It is happening because Wok is installing a /etc/logrotate.d/wokd.in file which is a template file and does not have the correct syntax according to logrotate.

We should keep this template internally and only install/generate the /etc/logrotate.d/wokd file

**Comment by ramonmedeiros** [comment]
@sureshab suggest to create the wokd.in in another place, to make possible to user to change some logrotate flags.

**Comment by ramonmedeiros** [comment]
Hi @sureshab,

i saw the discussion on the ML, about add a way to the user change logrotate parameters. Can you close this bug, since the main issue is solved and open another, to customize logrotate parameters?

**Comment by sureshab** [comment]
@ramonmedeiros  sure.
