### ISSUE TITLE
Make AsyncTask stoppable.

### ISSUE THREAD

**Issue by pvital** [kimchi-project/wok#122]
Cloned from https://github.com/kimchi-project/kimchi/issues/78 since it's not a Kimchi feature anymore.

Currently AsyncTask cannot be stopped by users, making it stoppable will help people when the job last too long or it already achieved the result people want (i.e.:expected isos found in the scan process).

**Comment by pvital** [comment]
This is an RFC for "Make AsyncTask stoppable" in Wok (and any other plugin). The main idea is give to user a way to stop a Task that is still running, cleaning all references and processes and setting the Task status to "killed".

To do this, the Task API need to be modified, by implementing the DELETE method in Task Resource. Said that, the API will look like:

```
### Resource: Task

**URI:** /tasks/*:id*

A task represents an asynchronous operation that is being performed by the
server.

**Methods:**

* **GET**: Retrieve the full description of the Task
    * id: The Task ID is used to identify this Task in the API.
    * status: The current status of the Task
        * running: The task is running
        * finished: The task has finished successfully
        * failed: The task failed
        * killed: The task was killed by user
    * message: Human-readable details about the Task status
    * target_uri: Resource URI related to the Task
* **DELETE**: Delete the Task
* **POST**: *See Task Actions*
**Actions (POST):**

*No actions defined*
```

Since an AsyncTask is basic a thread running in the system and this thread can execute a pure Python method or a background command (by using run_command() from wok.utils), the developer must pass as argument to the add_task() a method to be executed by the DELETE operation, called here as 'kill_cb'. With this idea, the add_task() method and also the AsyncTask constructor will be like:

```
def add_task(target_uri, fn, objstore, kill_cb=None, opaque=None):

class AsyncTask(object):
    def __init__(self, id, target_uri, fn, objstore, kill_cb=None, opaque=None):
```

If none kill_cb is passed, the task will not be able to stopped and an error (or warning) message will be raised to user if DELETE operation is executed. Otherwise, the kill_cb method will be executed by kill() method (responsible to execute the DELETE operation) of AsyncTask class and its status set to 'killed'.

The following RFC was sent to ML to discussion..

**Comment by pvital** [comment]
Based on feedback from ML about the proposed RFC, the add_task() method and also the AsyncTask constructor will be:

```
def add_task(target_uri, fn, objstore, opaque=None, kill_cb=None):

class AsyncTask(object):
    def __init__(self, id, target_uri, fn, objstore, opaque=None, kill_cb=None):
```

This will prevent the many calls already implemented using the opaque argument.

**Comment by pvital** [comment]
It's necessary to have a control of the AsyncTasks objects created by users to implement this solution. So, a dictionary will be used to control the objects and all information will be moved from objectstore to this dictionary.

**Comment by alinefm** [comment]
The infrastructure is already done in Wok. Each plugin which wants to make it available need to proper configure the Task to have a kill method.
