### ISSUE TITLE
nginx won't start after reboot

### ISSUE THREAD

**Issue by OnigamiSama** [kimchi-project/wok#123]
Si I have a fesh install of CentOS7.2 with Kimchi fully working since I had to reboot my server and now nginx won't start due to some errors in wok.conf

[root@zutsuu ~]# systemctl status nginx.service
● nginx.service - The nginx HTTP and reverse proxy server
   Loaded: loaded (/usr/lib/systemd/system/nginx.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2016-06-02 03:31:19 CEST; 11s ago
  Process: 1439 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)
  Process: 1437 ExecStartPre=/usr/bin/rm -f /run/nginx.pid (code=exited, status=0/SUCCESS)

Jun 02 03:31:19 zutsuu systemd[1]: Starting The nginx HTTP and reverse proxy server...
Jun 02 03:31:19 zutsuu nginx[1439]: nginx: [emerg] "user" directive is not allowed here in /etc/nginx/conf.d/wok.conf:25
Jun 02 03:31:19 zutsuu nginx[1439]: nginx: configuration file /etc/nginx/nginx.conf test failed
Jun 02 03:31:19 zutsuu systemd[1]: nginx.service: control process exited, code=exited status=1
Jun 02 03:31:19 zutsuu systemd[1]: Failed to start The nginx HTTP and reverse proxy server.
Jun 02 03:31:19 zutsuu systemd[1]: Unit nginx.service entered failed state.
Jun 02 03:31:19 zutsuu systemd[1]: nginx.service failed.

If I remove the line where the user directive is, it say that the line below is also wrong, and so on, so I've juste deleted wok.conf and nginx start but Kimchi web interface still doesn't work.

**Comment by pvital** [comment]
@OnigamiSama 

Yes, the file stored in /etc/nginx/conf.d/ is used to be loaded only when running nginx manually (that wokd starts automatically). The point, is that the same lines reported in the nginx log were loaded by the default configuration file of nginx.

You have two options here:

1. You can remove the common lines from /etc/nginx/conf.d/wok.conf (check the lines from the default config file of nginx and remove them); or
2. Disable nginx.service to be started automatically in system boot (if you don't use nginx for any other reason than wok).

I'm going to submit a patch to make wokd to use the system's nginx instead of start a new nginx process, then this issue will be solved.

**Comment by OnigamiSama** [comment]
I have disabled nginx to start at boot but I still can't acces the Kimchi webui.

/var/log/wok/wok-error.log : 
Loading YumUpdate features.
[02/Jun/2016:18:11:21] ENGINE Listening for SIGHUP.
[02/Jun/2016:18:11:21] ENGINE Listening for SIGTERM.
[02/Jun/2016:18:11:21] ENGINE Listening for SIGUSR1.
[02/Jun/2016:18:11:21] ENGINE Bus STARTING
[02/Jun/2016:18:11:21] ENGINE Serving on 127.0.0.1:8010
*** Running feature tests ***
*** Feature tests completed ***
*** Running feature tests ***
internal error: Child process (/usr/sbin/showmount --no-headers --exports localhost) unexpected exit status 1: clnt_create: RPC: Timed out

*** Feature tests completed ***
[02/Jun/2016:18:12:22] ENGINE Bus STARTED

I have the same issue displayed in systemctl status libvirtd.service

[root@zutsuu ~]# systemctl status libvirtd.service
● libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-06-02 18:07:39 CEST; 8min ago
     Docs: man:libvirtd(8)
           http://libvirt.org
 Main PID: 1221 (libvirtd)
   CGroup: /system.slice/libvirtd.service
           ├─1221 /usr/sbin/libvirtd
           ├─1304 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
           └─1305 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper

Jun 02 18:07:40 zutsuu dnsmasq[1304]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
Jun 02 18:07:40 zutsuu dnsmasq-dhcp[1304]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Jun 02 18:08:46 zutsuu libvirtd[1221]: libvirt version: 1.2.17, package: 13.el7_2.4 (CentOS BuildSystem <http://bugs.centos.org>, 2016-03-3...ntos.org)
Jun 02 18:08:46 zutsuu libvirtd[1221]: internal error: Child process (/usr/sbin/showmount --no-headers --exports localhost) unexpected exit...Timed out
Jun 02 18:08:47 zutsuu libvirtd[1221]: unsupported configuration: memory hotplug isn't supported by this QEMU binary
Jun 02 18:11:02 zutsuu libvirtd[1221]: End of file while reading data: Input/output error
Jun 02 18:11:02 zutsuu libvirtd[1221]: End of file while reading data: Input/output error
Jun 02 18:11:02 zutsuu libvirtd[1221]: End of file while reading data: Input/output error
Jun 02 18:12:21 zutsuu libvirtd[1221]: internal error: Child process (/usr/sbin/showmount --no-headers --exports localhost) unexpected exit...Timed out
Jun 02 18:12:22 zutsuu libvirtd[1221]: unsupported configuration: memory hotplug isn't supported by this QEMU binary
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by OnigamiSama** [comment]
Issue closed because initial issue is resolved
