### ISSUE TITLE
User activity Hygiene User activity logs can be improvised to provide file modification and creation logs

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#125]
#=== Problem Description ===================================
#===========================================================
Failure message are not captured well but right now it simply logs what action performed. However it is good know information like unauthorized person logged in to system with invalid user credentials.
Good to have more details in the user activity logging when let us say a particular file is modified or created etc. . These details are not shown in "User activity log" at the moment. If we can provide such information, it is easy for the admins to track what /when/where went wrong
Good to log IP address from which user logged in.

**Comment by alinefm** [comment]
It is the same as requested in #100.
So I will close this issue.
