### ISSUE TITLE
User activity [FVT] - The download of user acitvity logs with advanced search and then reset to default is incorrect..

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#127]
#=== Problem Description ===================================
#===========================================================
The download of user activity log does not download proper logs. The advanced search is performed on the default logs using any field and then reset to default and the log is downloaded . The log resulting from advanced search are downloaded instead of the default logs.

#=== Steps to Reproduce ====================================
#===========================================================
1. Perform user activity on the machine.
2. Press the advanced search tab and search the log using any field.
3. The press the reset to default tab and press the download tab.

**Comment by alinefm** [comment]
Wasn't it fixed by cd32405dd83ce5d9ab12f8bd3a138af0d0bc257d ?
