### ISSUE TITLE
Kimchi is logging out due to session timeout even when user is typing or using the webpage

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/wok#133]
Background
---------------
Kimchi logging out due to session time-out even when webpage is being used.

Login into Kimchi and used it for migration scenarios, 

1, During migration webpage was idle for some time which was less than timeout time as I was able to click "Actions" menu and selected migrate

2. When I used the webpage to start another migration and was typing the remote server IP kimchi got logged out automatically due to session time-out.

Ideally kimchi should not time-out when user is accessing or typing in the webpage.

Details
---------------
Wok is responsible for user session. That means on each server request, the user session is refreshed.

What (I suppose) it is happening here is you are playing on UI without effectively do any server request and when you do a request the session was already expired.

I agree it is not a good user experience. So thinking about a solution, we should refresh the user session (ie, send a server request) when open any UI dialog to collect user input. That way, we make sure to only open the dialog with a valid user session.
But it will not eliminate the case when user opens a dialog and keep it open for a long time to get the user session expired.

---------------
But it will not eliminate the case when user opens a dialog and keep it open for a long time to get the user session expired.

It will be good if we could refresh user session based on key press, mouse clicks and scrolling, so that session expires only if user opens a dialog box or log into kimchi and does nothing for time configured to timeout.

**Comment by laggarcia** [comment]
+1

That happened with me as well while I was playing with the firmware update feature and I wasn't sure what was going on.

**Comment by samhenri** [comment]
I think we can check if any input element is active / focused with jQuery a few seconds before the session timeout (currently 10 min). The idea is to put a function in Wok that start a 9:59 counter (or less) and just before the session ends, it will use a simple jQuery check to get elements with `:focus` or `:hover` on. If it returns true, then send a get config request to prevent the session timeout for 10 minutes. If it returns false or an empty array of elements, then it continues to the session timeout.

I think Wok should have a page to let users decide if they want to enable or disable the session timeout and set the minutes for this. @alinefm @sstoppler any comments?

**Comment by laggarcia** [comment]
I think your proposal would not work for all cases, @samhenri. If a user stays in front of a window typing for 5 minutes without submitting anything to the back end, and, then, they stop doing anything, your proposal would think the session should expire, while the user would have at least 5 more minutes before session timeout (considering a 10 minute session timeout). Said that, I think your proposal is bettern than what we have today.

However, with the disclaimer that I know nothing about how web UI works, I want to make a different proposal. Is it possible to create a thread in the Javascript that receives all user inputs (key press and mouse clicks) in parallel with the other UI elements we already have today? That way, if a user is typing in a text field, the characters will be registered in the text field as they would today, but each key press would also trigger an event on this separate thread. This separate thread would basically register the timestamp when a key press or mouse click event happened in a global variable (e.g. `last_key_event`). The same way, we would have another global variable (e.g. `last_back_end_access`) with the timestamp of the last request sent to the back end. That variable would be updated every time a request is made to the back end. Then, yet another Javascript thread would check `last_back_end_access` (let's say, every 5 seconds). If the session timeout is going to be reached, but `last_key_event` is less than the timeout value, we should refresh the session and reset the global variables.

**Comment by samhenri** [comment]
@laggarcia If the user keeps the cursor on, when the session reaches almost 10 minutes it would request a JSON to bypass the session timeout. The focus event is triggered when the browser cursor is active in any interactive element either by click or tab. As I was explaining to @alinefm and @sstoppler on e-mail, watching every key press would decrease performance to a point that it would impact user experience. I think the timestamp is a good idea though. The session timeout could happen between "user typed all inputs and is now moving mouse cursor to submit button", using timestamps would avoid this kind of problem.

BTW, there's also an accessibility issue here because once the screen reader software "jumps" to an element, it keeps active in the screen reader software context and not in the browser window. Only if the user hits enter that the screen reader software will set the selected element as "active" or "focused". It may take longer than 10 minutes to "read" the whole screen.

**Comment by peterpennings** [comment]
I want to suggest a new approach here. I guess we can divide it into two parts. 

1: A new tab in Wok allowing the user to set the session duration he wants (like a parameter). This tab can be named "config". In the future we can develop more options on this tab to set more parameters. What I am suggesting here, is an option to user set the session duration. We can do this by differents ways. It's just an idea.

2: When the session is almost expiring, we can show a dialog warning the user about it with an option to renew the session. For example: "Your session will be expired in 30 seconds. Do you want to renew it?" So then an "Ok" button on the bottom of the dialog. If no action is taken, the session will usually expire in 30 seconds. If the user press "Ok" the session will be refreshed to the duration he set, the dialog will be closed and he can keep working normally.

@laggarcia  @alinefm @samhenri @sstoppler @danielhb

**Comment by alinefm** [comment]
Hi @ramonmedeiros 

Please, make sure the backend is providing the data required for the UI.
Align that with @peterpennings

**Comment by ramonmedeiros** [comment]
Ok @peterpennings

**Comment by peterpennings** [comment]
Hi @ramonmedeiros, @samhenri   

After some discussion with @alinefm about the requirements of this issue, we conclude that at the moment we will work only on the second part of the above proposal. So the main idea to attack it is to put the time for the session ends in the header of each request/response. The UI will retrive this information and keep a timer with this info to fire the dialog modal at the right time. 

The dialog will give the option to renew the session, so an endpoint will be necessary in case of user choose to renew the session in the server. So when the user press Ok to renew, a request will be fired to do it.

So, if I'm not forgetting anything, we need the alias of this header parameter and the api to renew the session.

Any questions, let us know.

Tks

**Comment by alinefm** [comment]
To renew the user session we need to use a API which is protected by authentication.
So I'd suggest to use GET /tasks

@peterpennings @ramonmedeiros  Any objection?

**Comment by sstoppler** [comment]
Patch has been sent to ML for review.
I just tested it.

**Comment by alinefm** [comment]
The UI patch was applied upstream (23d785c655059f8b6b1bb5bf9a4d9428921cf586) but right after the login the dialog appears/disappear fast in the screen.
We need to fix that.

**Comment by sstoppler** [comment]
@peterpennings Any updates?

**Comment by peterpennings** [comment]
hi Socorro,

We already sent a patch to fix it. But there is another problem related to
a blink on the page when the UI is looking for some cookies on the login
action. We are investigating it.

2016-08-18 17:58 GMT-03:00 sstoppler <notifications@github.com>:

**Comment by pvital** [comment]
@peterpennings could you point me your patches and give us an update?

**Comment by peterpennings** [comment]
Hello Paulo,

Patch: [PATCH] [Wok 3/3] User session timeout alert (UI)
           [PATCH] [Wok] Wok BugFix - session message appearing on login

We are investigating the problem reported by alinefm about the dialog blink
on user login.

Tks

Peter

2016-08-30 11:40 GMT-03:00 Paulo Vital <notifications@github.com>:

**Comment by sstoppler** [comment]
Patch applied upstream:  https://github.com/kimchi-project/wok/commit/cdb3c4eafe222f9441b7c2eeba6d44764d9ec0e0
