### ISSUE TITLE
wok confirm window customization

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/wok#135]
wok.confirm.js is neither configurable to have single button in pop-up nor to configure the icon shown in the pop-up.
in multiple scenarios its required to provide a pop window having single button and "information" icon for example in "add user" if the "password" and "confirm password" doesn't match, it should provide pop with one button, not two..and its not warning, its error or information.

![screenshot from 2016-06-13 17 05 34](https://cloud.githubusercontent.com/assets/12499230/16006380/70d5adb8-318a-11e6-8492-b578a667e3df.png)

**Comment by alinefm** [comment]
If it is an error, why do not display it as an error message? Why do you need a pop up?

**Comment by sureshab** [comment]
yes, i get your point.closing this issue
