### ISSUE TITLE
Changes for User Log UI

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/wok#136]
Part 1 - fixes and adjusts to show timezone and user IP address
---------------------------------------------------------------------------------
1) Fix this issue: Date being showed by UI is one day before date returned by backend.
2) Show timezone in UI ("zone" field)
3) Show user IP address in UI ("ip" field)
4) Remove "search by time" from advanced search UI
5) Add "search by user IP" to advanced search UI

Part 2 will be defined once the logging of failed actions is upstream.

**Comment by samhenri** [comment]
Patch sent to ML.

**Comment by alinefm** [comment]
Fixed by 5354ce2e97d09092afce4ee7fc75b0dbb24da56f
