### ISSUE TITLE
The wok is unstable.The UI page does not come up.

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#138]
While trying to install the latest wok the UI does not come up. It displays a404 error.
I tried rolling back  2 previous commits with the commit id  a9986f581eed4f1f034fcbc620c639f802ad1e2f and  a9986f581eed4f1f034fcbc620c639f802ad1e2f after which the UI is working fine.

**Comment by danielhb** [comment]
Hi @mesmriti 

When you say "install" do you mean installing the RPM/Deb package? Which Linux did you use? Have you tried to run WoK standalone or did you load other plug-ins too?

**Comment by mesmriti** [comment]
I pulled the latest code from the githhub . Yes I tried the wok alone as well as with the plugins, it displayed the same error on the ui page. I tested it on  x86_64 machine.


![screenshot from 2016-06-21 14 50 14](https://cloud.githubusercontent.com/assets/13163405/16224433/b7f59bdc-37bf-11e6-837a-a5200c944db6.png)

**Comment by danielhb** [comment]
Hey Megha I think it's fixed upstream now. Please retest and let me know how it goes

**Comment by mesmriti** [comment]
Yes its working fine now. Thankyou.
