### ISSUE TITLE
Do not generate logrotate config file on the fly

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/wok#139]
per issue #118, raising new issue for option to customize logrotate parameters for wok

IMO we can move the logrotate template from server.py to wok_conf and read from there or as per ML discussion, have a file wokd.logrotate.in in /etc/wok for logrotate options. The same has be documented if needed.

**Comment by alinefm** [comment]
Hi @sureshab 

Which parameters do you want to customize on logrotate file? Could you elaborate your proposal?

**Comment by sureshab** [comment]
@alinefm 
there can be multiple parameters like how frequently logs have to be rotated, should it be compressed, mail settings etc.
IMO,
user might have his own log settings,,,but restarting of wokd shouldn't override his settings.

here is an example:
i modified /etc/logrotate.d/wokd with monthly rotation, and mailto settings.
when i restarted wokd,, default wokd settings were loaded except size.
