### ISSUE TITLE
User Activity Log Perms

### ISSUE THREAD

**Issue by gorjan-stojchev** [kimchi-project/wok#146]
User Activity Log visible under wok --> settings for every user despite `<access role="user" mode="none"/>` placed under ui/config/tab-ext.xml file.

**Comment by peterpennings** [comment]
There are two steps to solve this issue:

- BackEnd: The Wok tab should be considered a plugin. There is a cookie named roles, which has roles information through /login API. This API give the roles authorization for each plugin.

- FronEnd: As Wok have just one panel (Settings), it's necessary to make a logic on frontend to hide the parent tab when no panel is available for the user.
