### ISSUE TITLE
Hygiene - Unable to 'Download' a set of filtered 'User Activity Log' entries

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#149]
#=== Steps to Reproduce ====================================
#===========================================================
1.In the 'User Activity Log' filter on a value for specific 'message', ie: activate
2.Now I want to 'Download' just those entries from the filtering.
3.The 'Download' shows all entries, not just the 'filtered' ones.
4.This should work like the 'Advanced Search' now option does.

**Comment by lcorreia** [comment]
This is working by design, since the filtering is a UI feature which data backend does not have access to. The Download button will work only for the last result of Advanced Search.

**Comment by alinefm** [comment]
Closing based on last comment.
