### ISSUE TITLE
HYGEINE- Host system 'Restart' or 'Shutdown' task is not getting logged into the 'User Activity Log'

### ISSUE THREAD

**Issue by mesmriti** [kimchi-project/wok#150]
#=== Problem Description ===================================
#===========================================================
The Host system 'Restart' or 'Shutdown' task is not getting logged into the 'User Activity Log', and I think this type of task should be logged.

#=== Steps to Reproduce ====================================
#===========================================================
1. Perform a host restart or shutdown via the HVM gui.
2. View the User Activity Log, and do not see any such activity being logged.

**Comment by lcorreia** [comment]
Despite shutdown/restart action is instantaneous, I can see both of them logged (see screenshot from RHEL 7.2 vm). There were changes in backend meanwhile that may have solved this issue. 
![reboot-shutdown](https://cloud.githubusercontent.com/assets/1502838/18790590/bb1c569c-8185-11e6-80e1-ddcf44e91804.png)
