### ISSUE TITLE
Wok settings page not working when locale not set

### ISSUE THREAD

**Issue by bobvandevijver** [kimchi-project/wok#151]
I can not open the settings page under Wok when the locale is not set on the login page. The following trace in the wok-error.log is found:

```
[19/Jul/2016:14:53:54] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/wok/root.py", line 131, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/dist-packages/wok/template.py", line 117, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/dist-packages/wok/template.py", line 103, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_ui_pages_tabs_settings_html_tmpl.py", line 105, in respond
  File "/usr/lib/python2.7/gettext.py", line 469, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'wok'
```

Probably the login form needs to enforce default for the language and locale fields, and should not be allowed to be empty.

**Comment by alinefm** [comment]
Hi @bobvandevijver 

I never set locale on login page and have never seen the problem you described.
Which OS and browser you are using? Could you provide more details about your system and setup?

**Comment by bobvandevijver** [comment]
Hi @alinefm!

I can only reproduce this problem when I visit the login page for the first time, without a previous session. As you can see in the screenshot below, the language and locale dropdown fields are rendered empty (nothing is selected). 
![knipsel](https://cloud.githubusercontent.com/assets/1835343/18362819/96c87a34-7607-11e6-8235-ea218f3dfa10.PNG)

I can login fine, but the settings page does not work (with the error above in the logs). 
![knipsel](https://cloud.githubusercontent.com/assets/1835343/18362779/73aee33a-7607-11e6-9186-84f056771d0f.PNG)

Other pages work perfectly. After logging off, and selecting one of the language options, the page is reloaded and the value is probably set in the session, as from that point is no longer possible the clear the field without restarting without cookies (I'm using incognito-mode). When logging in when a selection is made in the language field, the settings page works fine.

I run a compiled version of Wok with Ginger, Gingerbase and Kimchi on a Debian Jessie system. The browser is, as you probably guessed, the latest Chrome.

Solution would be to have an default selected for the field. I'm not sure where to to that, otherwise I would make a PR :grinning:

**Comment by bobvandevijver** [comment]
Right, the browser settings make sense in this scenario. My browser has as default Dutch, which is not available for Wok. When I tell my browser to use en-us as default, indeed the English is selected. 

So, to fix the problem, the default language and locale guesser should always return en-us if the the browser language is not available.

**Comment by alinefm** [comment]
Hi @bobvandevijver 

Thanks for the details. We will work to fix that soon.

**Comment by aaronmailageek** [comment]
I used this workaround which seemed to solve the problem:

```
cp /usr/share/locale/en_US/LC_MESSAGES/gingerbase.mo  /usr/share/locale/en_GB/LC_MESSAGES/
cp /usr/share/locale/en_US/LC_MESSAGES/kimchi.mo  /usr/share/locale/en_GB/LC_MESSAGES/
cp /usr/share/locale/en_US/LC_MESSAGES/wok.mo  /usr/share/locale/en_GB/LC_MESSAGES/

```
log out and back in to the WebUI
