### ISSUE TITLE
Fail to start wokd, due to error in nginx proxy start service

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/wok#152]
With latest cloned code, I am getting following error on Fedora and S390x lpar-

wokd --host=0.0.0.0
WOKPROXY0001E: WOKPROXY0001E
Traceback (most recent call last):
  File "/usr/bin/wokd", line 106, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/wokd", line 103, in main
    wok.server.main(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 247, in main
    srv = Server(options)
  File "/usr/lib/python2.7/site-packages/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/usr/lib/python2.7/site-packages/wok/proxy.py", line 131, in start_proxy
    raise OperationFailed('WOKPROXY0001E', {'error': error})
wok.exception.OperationFailed: WOKPROXY0001E: WOKPROXY0001E

**Comment by pvital** [comment]
Commit 4cbb1b9 changed how NGINX is used by Wok. 

On Fedora/RHEL or systems that have SELinux in Enforcing mode, you have to follow the steps described at https://github.com/kimchi-project/wok/blob/master/docs/troubleshooting.md

**Comment by jay-katta** [comment]
I have followed those steps. 
Still getting same error.
Prior to this commit, I was not getting this error.

**Comment by danielhb** [comment]
@jay-katta try starting the nginx service:

sudo systemctl start nginx

Prior of using WoD

**Comment by pvital** [comment]
The new code execute the systemd command to restart nginx.service, so if it's not runing, it'll start when you start wokd. The line pointed by python trace is regarding, exactly to this command.

Please, try to start nginx.service manually, and if not start up, paste the output of nginx log.

**Comment by jay-katta** [comment]
Now I do not see any issue in starting the wokd service. 
Hence closing this issue.

Note: I did not start nginx service manually
