### ISSUE TITLE
http connection redirects to https when https_only is set to false

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/wok#154]
Per default settings, 8000 is used as http port and 8001 is used as
https port.
case 1: https_only=true, was not able to browse with 8000 port, which is
as expected. 
case 2: https_only=false, per my understanding, it should allow http
connections, but all the http requests are rerouted to https and 8001 port.

**Comment by pvital** [comment]
If https_only=false then 8000 should handle the connection and not redirect to 8001, IMO.

I guess the problem is in NGINX configuration, created by Wok start up process. It's redirecting port 8000 to 8001, even if https_only=false is set up.

**Comment by alinefm** [comment]
@sureshab @pvital 
The https_only option is to allow user disables the HTTP port which means only HTTPS will be up an running.
If you set it to False, the HTTP will be enabled but it will redirected to HTTPS by security matters.
If you set it to True, only HTTPS will be enabled, ie, :8000 will not work.

It is working as designed as I could confirm in the current master branch (8e5a84d592ab9efad6dd85da867af7356ae62999)
