### ISSUE TITLE
'make clean' does not revert its changes from 'make rpm'

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/wok#155]
After running make rpm, if you run make clean to clean all the build artifacts and get a clean source tree again, you'll still have files left from the make rpm process.

Steps to reproduce:

1) make rpm
2) make clean
3) git status

On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   ChangeLog
	modified:   po/de_DE.po
	modified:   po/en_US.po
	modified:   po/es_ES.po
	modified:   po/fr_FR.po
	modified:   po/it_IT.po
	modified:   po/ja_JP.po
	modified:   po/ko_KR.po
	modified:   po/pt_BR.po
	modified:   po/ru_RU.po
	modified:   po/wok.pot
	modified:   po/zh_CN.po
	modified:   po/zh_TW.po
	modified:   src/wok/plugins/sample/po/en_US.po
	modified:   src/wok/plugins/sample/po/pt_BR.po
	modified:   src/wok/plugins/sample/po/sample.pot
	modified:   src/wok/plugins/sample/po/zh_CN.po

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by alinefm** [comment]
The patch applied upstream does not fix the issue.It reverts the changes made by 'make rpm' instead of prevent 'make rpm' to modify changes.
