### ISSUE TITLE
Session will be expire in 30s

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/wok#157]
We are getting session will expire in 30s pop up every time we login or navigate through pages.
Session is actually not getting expire in 30s. Attached screen shot 

![session](https://cloud.githubusercontent.com/assets/511072/17809764/6dc3fdce-6636-11e6-9c9d-9e1667cb38a9.png)

**Comment by danielhb** [comment]
This is an issue I've talked about once with @peterpennings and/or @samhenri (can't recall which one now) . It's something to do with how the page is being rendered before checking if the user session is valid.

Peter/Samuel any comments? Is it easy to fix?

**Comment by alinefm** [comment]
Fixed by cdb3c4eafe222f9441b7c2eeba6d44764d9ec0e0
