### ISSUE TITLE
Some messages are truncated by User Log UI

### ISSUE THREAD

**Issue by lcorreia** [kimchi-project/wok#161]
Messages containing the \" combination are being truncated in User Log UI.

Example:
"The debug report with specified name \"%(name)s\" already exists." will be showed as "The debug report with specified name "

In order to reproduce it, run gingerbase tests to see truncated error messages generated in User Log. Replacing \" by ' fixes the issue, but there are many occurrences. Perhaps there is a better solution with escaping.

**Comment by alinefm** [comment]
Patch sent to Ginger Base.
