### ISSUE TITLE
Fedora 24: make rpm from dist tarball error

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/wok#162]
Running 'make rpm' in Fedora 24 gets the following errors:

``` javascript
$ make rpm
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/bcarvalho/Documents/kimchi/wok/teste/wok-2.2.0'
/bin/sh: line 1: ./build-aux/genChangelog: No such file or directory
Makefile:1025: recipe for target 'ChangeLog' failed
make[1]: *** [ChangeLog] Error 127
make[1]: Leaving directory '/home/bcarvalho/Documents/kimchi/wok/teste/wok-2.2.0'
Makefile:708: recipe for target 'dist' failed
make: *** [dist] Error 2
```

**Comment by ramonmedeiros** [comment]
Just tested here. It's working.

Steps:
1) Copy tarball to a new folder
2) Extract it
3) Run ./autogen.sh --system && make
4) make rpm

http://pastebin.com/zmi0GHt7. Can i close it?

**Comment by biancafc** [comment]
I've tried again with all steps and still getting the same error, take a look: http://pastebin.com/JET2XG5n

**Comment by biancafc** [comment]
Please, ignore my previous message, I was testing with wok-2.2.0 not wok-2.3.0. Everything is working fine.
