### ISSUE TITLE
Wok is not creating /usr/local/etc/nginx/conf.d/

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/wok#170]
After patch 4cbb1b93d62fb0b3ac0a2d5ece89d9b01f710b61, kimchi can use /usr/local to change some configs. But, if the path does not exists, kimchi isn't dealing with that, causing the error:

```
ramonn@jarvis:~/GitTrees/WOK (newJstoRpm *)$ sudo ./src/wokd --environment=b
> /home/ramonn/GitTrees/WOK/src/wok/proxy.py(118)_create_proxy_config()
-> if not paths.installed:
(Pdb) n
> /home/ramonn/GitTrees/WOK/src/wok/proxy.py(119)_create_proxy_config()
-> dst = os.path.join(paths.sys_nginx_conf_dir, "wok.conf")
(Pdb) print sys_nginx_conf_dir
*** NameError: name 'sys_nginx_conf_dir' is not defined
(Pdb) print paths.sys_nginx_conf_dir
/usr/local/etc/nginx/conf.d
(Pdb) c
Traceback (most recent call last):
  File "./src/wokd", line 106, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./src/wokd", line 103, in main
    wok.server.main(options)
  File "/home/ramonn/GitTrees/WOK/src/wok/server.py", line 247, in main
    srv = Server(options)
  File "/home/ramonn/GitTrees/WOK/src/wok/server.py", line 77, in __init__
    start_proxy(options)
  File "/home/ramonn/GitTrees/WOK/src/wok/proxy.py", line 127, in start_proxy
    _create_proxy_config(options)
  File "/home/ramonn/GitTrees/WOK/src/wok/proxy.py", line 119, in _create_proxy_config
    dst = os.path.join(paths.sys_nginx_conf_dir, "wok.conf")
OSError: [Errno 2] No such file or directory
```

**Comment by pvital** [comment]
@ramonmedeiros I have some question about this issue:

1. How did you built wok?
2. Was wok installed on the system (looks like from the pasted output you're runnning from devel path)?
3. What host OS did you used? Was nginx installed by the default package manager?

Thanks

**Comment by alinefm** [comment]
I think the nginx directory depends on nginx package. 
If nginx is not installing this directory, we should look for which one is used to handle configuration files.
I don't think creating a directory by hand is a solution.
It also applies to #166 solution.

**Comment by pvital** [comment]
We use the sys_nginx_conf_dir from wok.config.paths to set the paths of nginx. From the source code, the variable is set as:

```
self.sys_nginx_conf_dir = '@sysconfdir@/nginx/conf.d'
```

The variable sysconfigdir is set by configure when autogen.sh is executed, depending on the arguments passed.  Here is the portion of autogen.sh that sets it:

```
if [ "x$1" == "x--system" ]; then
    ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var
else
   if [ $# -gt 0 ]; then
        ./configure $@
   else
        ./configure --prefix=/usr/local
   fi
fi
```

If your environment is using the path "/usr/local/etc/nginx/conf.d" as config dir for nginx, you executed autogen.sh without --system argument.

**Comment by ramonmedeiros** [comment]
You are right. Just notice that i found this when i was changing configure.ac to accept new parameter. I forget the --system parameter.


The bug does not exist.
