### ISSUE TITLE
Yet another server trashed as a result of Kimchi installation process

### ISSUE THREAD

**Issue by philled** [kimchi-project/wok#178]
I've reported here before that two previous attemps to install Kimchi on a KVM Ubuntu 16.04 host has resulted in such a messed up set of package dependencies that I've had to rebuild the server both times. 

So I've spent the last few weeks trying to install Kimchi on a VM running on the KVM host Kimchi's trying to manage, but no matter what I try I can't get any VMs to show up in the web interface. Another poor soul has been battling with the same issue.

So...with some trepidation I decided to try installing directly on the KVM host again. And now I'm in dependency hell again :(

The problem I'm having is when installing the wok deb package I get this:

```
$ sudo dpkg -i wok-2.3.0-0.noarch.deb
(Reading database ... 212240 files and directories currently installed.)
Preparing to unpack wok-2.3.0-0.noarch.deb ...
Unpacking wok (2.3.0) over (2.3.0) ...
dpkg: dependency problems prevent configuration of wok:
 wok depends on nginx; however:
  Package nginx is not configured yet.
  Package nginx-full which provides nginx is not configured yet.

dpkg: error processing package wok (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.7.5-1) ...
Errors were encountered while processing:
 wok
```

This is what happens If I try to re-install nginx:

```
$ sudo apt-get install nginx-full
Reading package lists... Done
Building dependency tree
Reading state information... Done
nginx-full is already the newest version (1.10.0-0ubuntu0.16.04.4).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up nginx-full (1.10.0-0ubuntu0.16.04.4) ...
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
dpkg: error processing package nginx-full (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of nginx:
 nginx depends on nginx-core (>= 1.10.0-0ubuntu0.16.04.4) | nginx-full (>= 1.10.0-0ubuntu0.16.04.4) | nginx-light (>= 1.10.0-0ubuntu0.16.04.4) | nginx-extras (>= 1.10.0-0ubuntu0.16.04.4); however:
  Package nginx-core is not installed.
  Package nginx-full is not configured yet.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.
 nginx depends on nginx-core (<< 1.10.0-0ubuntu0.16.04.4.1~) | nginx-full (<< 1.10.0-0ubuntu0.16.04.4.1~) | nginx-light (<< 1.10.0-0ubuntu0.16.04.4.1~) | nginx-extras (<< 1.10.0-0ubuntu0.16.04.4.1~); however:
  Package nginx-core is not installed.
  Package nginx-full is not configured yet.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.

dpkg: error processing package nginx (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of wok:
 wok depends on nginx; however:
  Package nginx is not configurNo apport report written because the error message indicates its a followup error from a previous failure.
         No apport report written because the error message indicates its a followup error from a previous failure.
                                                                                                                   ed yet.
  Package nginx-full which provides nginx is not configured yet.

dpkg: error processing package wok (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nginx-full
 nginx
 wok
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Can anyone please advise what I need to do to sort out the nginx issue so I can install wok?

**Comment by alinefm** [comment]
Please, follow the steps described at http://kimchi-project.github.io/wok/downloads/

**Comment by philled** [comment]
I've sorted out the nginx problem by doing this:

`$ sudo apt-get remove nginx* && sudo apt-get install nginx-full`

Then run sudo dpkg -i <wok.deb> again

**Comment by philled** [comment]
Hi Aline, the problem with those instructions is that they seem to be
incomplete. They give the impression that installing Kimchi is extremely
simple, but in my eperience there are a number of hurdles that people will
come up against which aren't documented here. I know I'm not the first
person to say that the Kimchi documentation could be much better.

I'd be happy to provide the step by step instructions I had to follow to
get it working, but it needs to be posted somewhere people can find it. If
it's just captured in the issues somewhere that doesn't really help people
very much.

Please let me know if I can post my installation steps somewhere. Once I've
tried it again and confirmed on another machine I'd be happy to post them.

Regards,
Phill

**Comment by alinefm** [comment]
I am curious to know what you needed to do more than:

```
sudo dpkg -i wok.dev
sudo apt-get install -f
```

And of course you can share your found with others. You can create a new wiki page in github to that. Please, add a new page under https://github.com/kimchi-project/wok/wiki

**Comment by philled** [comment]
Apologies, I posted this in the wrong place. I meant to post it against Kimchi rather than Wok.

**Comment by alinefm** [comment]
Hi @philled 
Have you posted the instructions somewhere?
I will close this issue by now. Please, reopen if needed.
