### ISSUE TITLE
Downloading old versions of the packages

### ISSUE THREAD

**Issue by indyspike** [kimchi-project/wok#179]
The readme.md file cites a location for downloads as
wget http://kimchi-project.github.io/ginger/downloads/ginger-2.0.0-0.noarch.deb
I get a 404 for this location. 
http://kimchi-project.github.io/ginger/downloads/ reports it's version 2.3.0 with no links to previous versions for older versions of the packages.
I understand the desire to keep compatibility with the latest distro versions, but having access to the older versions with the understanding that they are unsupported would be a good idea.

**Comment by alinefm** [comment]
Hi @indyspike 

The problem you reported is about Ginger. I will replicate the issue on https://github.com/kimchi-project/ginger/issues/ and close this one.

Ginger issue: https://github.com/kimchi-project/ginger/issues/504
