### ISSUE TITLE
List Bug and Feature

### ISSUE THREAD

**Issue by microm22** [kimchi-project/wok#181]
Hello,

I am currently on an Ubuntu 16.04.1 LTS Server with the packages installed for the proper functioning of Wok, GingerBase, Ginger and Kimchi.
This is my list of currently errors and features watch after I test this kimchi-project.  

- [Bug] In **Host** -> **Network** -> **Network Configuration**
Selecting a Network Actions menu -> Settings = error "**Persistent file is not available for enp1s0 interface.**"

- [Bug] In **Host** -> **System Services** -> **System Services Management**
When I stop one of the services, I can't restart the service because the service has disappeared.

- [Bug] In **Virtualization** -> **Storage** -> **ISO** -> **Actions** -> **Add Volume**
The upload files of stops during the changing tab or page. Therefore the file is corrupted. I also found on the Dashboard, the upload file via your web interface is well below the upload SSH.

- [Feature] Add restore function
In your web interface, you can make a backup of Wok settings, but what about the restoration of this parameter? I propose to add that we can restore Wok settings.

Thanks in advance.

**Comment by alinefm** [comment]
Hi @microm22 

Thanks for reporting all this. Some of those issue are already being addressed.
Could you explain better the upload problem you found? 
From what I understood, you started a upload process and then switched tabs and it makes the upload to stop and have a corrupted file on storage pool, Is that correct?
About the time, the upload from client to server must be done part by part due limitation on maximum body size for a HTTP request. Maybe that is the reason on why SSH is faster.

**Comment by alinefm** [comment]
1) It is being addressed by https://github.com/kimchi-project/ginger/issues/390 and https://github.com/kimchi-project/ginger/issues/394

2) It was addressed by https://github.com/kimchi-project/ginger/issues/414

3) I created a new bug to track the request: https://github.com/kimchi-project/kimchi/issues/1095

4) I created a new bug to track the request: https://github.com/kimchi-project/ginger/issues/517

I will close this issue by now. Thanks @microm22 for all the inputs.
