### ISSUE TITLE
make rpm fails on CentOS when firewalld isn't installed

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/wok#185]
done < po/LINGUAS
make[3]: Entering directory `/root/WOK/rpm/BUILD/wok-2.3.0'
make[3]: Nothing to be done for `install-exec-am'.
mkdir -p /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64//var/log/wok/
touch /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64//var/log/wok/wok-access.log
touch /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64//var/log/wok/wok-error.log
mkdir -p /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/etc/wok/
/usr/bin/install -c -m 644 src/dhparams.pem /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/etc/wok/dhparams.pem
touch /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/etc/nginx/conf.d/wok.conf
mkdir -p /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/etc/logrotate.d/
/usr/bin/install -c -m 644 ./src/wok.logrotate /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/etc/logrotate.d/wokd
 /usr/bin/mkdir -p '/root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/usr/share/man/man8'
 /usr/bin/install -c -m 644 docs/wokd.8 '/root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/usr/share/man/man8'
make[3]: Leaving directory `/root/WOK/rpm/BUILD/wok-2.3.0'
make[2]: Leaving directory `/root/WOK/rpm/BUILD/wok-2.3.0'
make[1]: Leaving directory `/root/WOK/rpm/BUILD/wok-2.3.0'
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /root/WOK/rpm/BUILD/wok-2.3.0
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.
find: 'debug': No such file or directory
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
+ /usr/lib/rpm/redhat/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Processing files: wok-2.3.0-23.git8da9647.el7.centos.noarch
error: File not found: /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/usr/lib/firewalld/services/wokd.xml

RPM build errors:
    File not found: /root/WOK/rpm/BUILDROOT/wok-2.3.0-23.git8da9647.el7.centos.x86_64/usr/lib/firewalld/services/wokd.xml
make: *** [rpm] Error 1

**Comment by alinefm** [comment]
Seems it is related to #27
