### ISSUE TITLE
Login as normal PAM user freezes google-chrome 

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/wok#187]
Steps to reproduce:

Server side:
CentOS 7.2
PAM authentications

Client Side:
normal user without sudo
Google Chrome
Fedora 24 x86

**Comment by biancafc** [comment]
Not sure if is the same problem, but when I try to login as normal user, I can't see any information. In browser URL field .../tabs/settings keeps blinking.

<img width="1405" alt="captura de tela 2016-11-30 as 12 00 45" src="https://cloud.githubusercontent.com/assets/6681745/20755148/06c7a9f8-b6f5-11e6-87a1-a24771586edf.png">

**Comment by alinefm** [comment]
Hi @ramonmedeiros and @biancafc 

Have you faced the same problem with admin users (with sudo)? Or the problem is strict related to non-admin users?

**Comment by ramonmedeiros** [comment]
Just with non-sudo users

**Comment by lcorreia** [comment]
Same on Ubuntu 16.10.

Got this from wok-error.log:
rc: 1 error:  returned from cmd: sudo -l -U test sudo

**Comment by biancafc** [comment]
@alinefm yes, it's only non-sudo users.
