### ISSUE TITLE
No translation file found for domain: 'wok'

### ISSUE THREAD

**Issue by jarredkenny** [kimchi-project/wok#192]
Hello,

On a fresh installation of Centos 7 I am having trouble running wok from the RPM distributed here: http://kimchi-project.github.io/wok/downloads/

```
[root@hv1-mc ~]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core)
```

When I start wok and navigate to the web interface, It allows me to log in but once logged in the initial wok tab never loads. The tabs provided by ginger-base and kimchi do not load either.

I see this error in woks error log:

```
[root@hv1-mc ~]# tail /var/log/wok/wok-error.log 
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_ui_pages_tabs_settings_html_tmpl.py", line 105, in respond
  File "/usr/lib64/python2.7/gettext.py", line 471, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'wok'
```

I have gotten around this issue by running wok/ginger-base/kimchi from source for the time being. However, I would prefer to use the distributed RPMs for systemd integration and version management.

**Comment by alinefm** [comment]
Hi @jarredkenny 

Thanks for reporting the issue.
Have you installed the latest version of Wok, Ginger Base and Kimchi? Any special setup on that?
I will try it again on CentOS 7 and let you know on any update.

**Comment by sammcj** [comment]
Yep I'm getting this too.

- CentOS Linux release 7.3.1611
- ginger-base-2.2.2-0.el7.centos.noarch
- ginger-2.3.1-0.el7.centos.noarch
- wok-2.3.1-0.el7.centos.noarch

```bash
[11/Feb/2017:14:07:23] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/root.py", line 130, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_plugins_ginger_ui_pages_tabs_host_storage_html_tmpl.py", line 105, in respond
  File "/usr/lib64/python2.7/gettext.py", line 471, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'ginger'
```

**Comment by P4z** [comment]
same thing here :(

```
root@localhost /v/l/wok# lsb_release -a; dpkg -l | grep -P "wok|ginger|kimchi"
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie
ii  ginger-base                    2.2.2                                 all          Ginger Base is an open source base host management plugin for Wok (Webserver Originated from Kimchi), that provides an intuitive web panel with common tools for configuring and managing the Linux systems.
ii  kimchi                         2.3.1                                 all          Kimchi web application
ii  wok                            2.3.1                                 all          Wok - Webserver Originated from Kimchi
```

```
[20/Feb/2017:19:27:56] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/wok/root.py", line 130, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/dist-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/dist-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_ui_pages_tabs_settings_html_tmpl.py", line 105, in respond
  File "/usr/lib/python2.7/gettext.py", line 469, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'wok'
```

**Comment by NotoriousPyro** [comment]
Same here and a lot of the pages in Wok don't display any information.
[26/Feb/2017:18:57:51] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/root.py", line 130, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_plugins_ginger_ui_pages_tabs_host_storage_html_tmpl.py", line 105, in respond
  File "/usr/lib64/python2.7/gettext.py", line 471, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'ginger'

[26/Feb/2017:18:57:53] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/root.py", line 130, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_ui_pages_tabs_settings_html_tmpl.py", line 105, in respond
  File "/usr/lib64/python2.7/gettext.py", line 471, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'wok'

**Comment by catborise** [comment]
Fedora25 and OEL7.3 same problem with packages like below

rpm -qa|grep -P "wok|ginger|kimchi"
kimchi-2.3.1-0.fc25.noarch
ginger-base-2.2.2-0.fc25.noarch
wok-2.3.1-0.fc25.noarch

rpm -qa|grep -P "wok|ginger|kimchi"
wok-2.3.1-0.el7.centos.noarch
kimchi-2.3.1-0.el7.centos.noarch
ginger-base-2.2.2-0.el7.centos.noarch

**Comment by boshido** [comment]
I got the same error on ubuntu 
lsb_release -a
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.10
Release:	16.10
Codename:	yakkety
```

dpkg -s wok
```
Package: wok
Status: install ok installed
Priority: optional
Section: base
Maintainer: Aline Manera <alinefm@br.ibm.com>
Architecture: all
Version: 2.3.1
Depends: python-cherrypy3 (>= 3.2.0), python-cheetah, python-jsonschema (>= 1.3.0), gettext, python-m2crypto, python-pam, python-lxml, nginx, python-ldap, python-psutil (>= 0.6.0), fonts-font-awesome, logrotate, texlive-fonts-extra
Description: Wok - Webserver Originated from Kimchi
Build-Depends: xsltproc,
               gettext,
               openssl,
               python-lxml,
               pkg-config
```

dpkg -s ginger-base
```
Package: ginger-base
Status: install ok installed
Priority: optional
Section: base
Maintainer: Daniel Henrique Barboza <danielhb@linux.vnet.ibm.com>
Architecture: all
Version: 2.2.2
Depends: wok (>= 2.1.0), python-apt, python-cherrypy3, python-configobj, python-lxml, python-parted, python-psutil (>= 0.6.0), gettext, git, sosreport
Description: Ginger Base is an open source base host management plugin for Wok (Webserver Originated from Kimchi), that provides an intuitive web panel with common tools for configuring and managing the Linux systems.
Build-Depends: libxslt,
               gettext,
               python-lxml
```

dpkg -s kimchi
```
Package: kimchi
Status: install ok installed
Priority: optional
Section: base
Maintainer: Aline Manera <alinefm@br.ibm.com>
Architecture: all
Version: 2.3.1
Depends: wok (>= 2.1.0), ginger-base, python-imaging, python-configobj, websockify, novnc, python-jsonschema (>= 1.3.0), python-libvirt, gettext, libvirt-bin, nfs-common, qemu-kvm, python-parted, python-psutil (>= 0.6.0), python-ethtool, sosreport, python-ipaddr, python-lxml, open-iscsi, python-guestfs, libguestfs-tools, spice-html5, python-magic, python-paramiko
Description: Kimchi web application
Build-Depends: xsltproc,
               gettext,
               python-lxml
```

**Comment by alinefm** [comment]
Hi all,

Could you check the following directory for me:

```
/usr/share/locale/*/LC_MESSAGES/
```

And verify there is a .mo file named as wok or ginger under the language you are using to access Wok interface.

**Comment by Vitexus** [comment]
Hallo, i have that same problem with todays packages on Debian Jessie and Stretch.

/usr/share/locale/en_US/LC_MESSAGES/:
-rw-r--r-- 1 root root   461 pro 15 14:25 gingerbase.mo
-rw-r--r-- 1 root root   457 pro 15 14:24 kimchi.mo
-rw-r--r-- 1 root root   510 říj 14  2014 virt-viewer.mo
-rw-r--r-- 1 root root   457 pro 15 14:25 wok.mo

**Comment by alinefm** [comment]
Which package versions are in Debian Jessie and Stretch?

I have tried using the packages available at http://kimchi-project.github.io/kimchi/downloads/ and it worked for me.

**Comment by Vitexus** [comment]
I also use your packages. 

ginger-base 2.2.2
wok 2.3.1
kimchi 2.3.1

The error is:

```
[22/Mar/2017:16:30:45] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/wok/root.py", line 129, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/dist-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/dist-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_ui_pages_tabs_user_log_html_tmpl.py", line 106, in respond
  File "/usr/lib/python2.7/gettext.py", line 545, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'wok'

```

**Comment by spaceheadx** [comment]
Same issue/error here for me after trying again with 2.4.0.

I can login, but not navigate to the "Settings" pages of Wok and Ginger, which makes Ginger/Kimchi basically unusable for me.

Did a fresh install of the machine yesterday and installed the latest RPMs for CentOS.

```
[root@machine ~]# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
[root@machine ~]# rpm -qa|grep -P "wok|ginger|kimchi"
kimchi-2.4.0-0.el7.centos.noarch
wok-2.4.0-0.el7.centos.noarch
ginger-base-2.3.0-0.el7.centos.noarch
ginger-2.4.0-0.el7.centos.noarch
```

Errors:
```
[31/Mar/2017:19:15:17] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/root.py", line 129, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_ui_pages_tabs_settings_html_tmpl.py", line 106, in respond
  File "/usr/lib64/python2.7/gettext.py", line 471, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'wok'

[31/Mar/2017:19:15:36] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/site-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/wok/root.py", line 129, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 133, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/site-packages/wok/template.py", line 108, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_plugins_ginger_ui_pages_tabs_host_settings_html_tmpl.py", line 105, in respond
  File "/usr/lib64/python2.7/gettext.py", line 471, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'ginger'
```

Locale settings:
```
[root@machine ~]# ls -lha /usr/share/locale/en_US/LC_MESSAGES/
total 52K
drwxr-xr-x. 2 root root 140 Mar 31 18:53 .
drwxr-xr-x. 3 root root  25 Mar 29 23:57 ..
-rw-r--r--. 1 root root 26K Mar  3 03:41 firewalld.mo
-rw-r--r--. 1 root root 461 Mar 29 17:32 gingerbase.mo
-rw-r--r--. 1 root root 427 Mar 29 17:32 ginger.mo
-rw-r--r--. 1 root root 457 Mar 29 17:31 kimchi.mo
-rw-r--r--. 1 root root 410 Dec  6 19:34 mit-krb5.mo
-rw-r--r--. 1 root root 490 Jan 17 23:31 policycoreutils.mo
-rw-r--r--. 1 root root 457 Mar 29 17:31 wok.mo

[root@machine ~]# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

I also experience this issue: https://github.com/kimchi-project/kimchi/issues/1109 (maybe unrelated)

Seems quite broken on CentOS 7 for me... :( Please let me know if you need any further information to help you identify the issues.

**Comment by JoseGoncalves** [comment]
Same problem here in a Debian 8.7 distro with latest Wok, Gingerbase and Kimchi packages, but only when using Chrome!

If I access Wok with Firefox all is OK, i,e,, no error is shown on the log and the Wok tab is correctly displayed.

**Comment by NotoriousPyro** [comment]
Firefox does the same as Chrome for me.

**Comment by alinefm** [comment]
I have only tried that on a fresh CentOS 7 installtion and it worked for me.
Have you done a fresh Wok/Kimchi installation? Or an upgrade from an older version?
I am just trying to collect as much information as I can to try to reproduce it in my system.

**Comment by alinefm** [comment]
Also I need to know the locale/language set in your browser settings. Wok does not rely on system settings.

**Comment by JoseGoncalves** [comment]
This was a fresh install of Wok/Gingerbase/Kimchi on a Debian 8.7 system.
The browsers that I user are set to English (US).
Please tell me if you need any further information.

**Comment by alinefm** [comment]
Ok. I will create a Debian and CentOS VMs and install the most recent Wok/Kimchi packages and turn back to you soon.

**Comment by alinefm** [comment]
Thanks for the detailed information @spaceheadx 

I will do some tests using locale/language as en_GB and turn back to you soon.

**Comment by spaceheadx** [comment]
if it helps, here is some additional information i gathered from http://www.localeplanet.com/support/browser.html:

Chrome:
```
navigator.browserLanguage: undefined
navigator.language: en-GB
navigator.userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36
date: Tue Apr 04 2017 15:12:49 GMT+0200 (CEST)
date.toLocaleDateString(): 04/04/2017
date.toLocaleTimeString(): 15:12:49
date.toLocaleString(): 04/04/2017, 15:12:49
date.toUTCString(): Tue, 04 Apr 2017 13:12:49 GMT
date.getTimezoneOffset(): -120
```
```
request.getLocale(): en_GB.
request.getLocales(): en_GB, en, en_US, de_DE, de.
```
Firefox:
```
navigator.browserLanguage: undefined
navigator.language: en-GB
navigator.userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0
date: Tue Apr 04 2017 15:13:02 GMT+0200 (CEST)
date.toLocaleDateString(): 04/04/2017
date.toLocaleTimeString(): 15:13:02
date.toLocaleString(): 04/04/2017, 15:13:02
date.toUTCString(): Tue, 04 Apr 2017 13:13:02 GMT
date.getTimezoneOffset(): -120
```
```
request.getLocale(): en_GB.
request.getLocales(): en_GB, en.
```

**Comment by NotoriousPyro** [comment]
My language settings are en_GB and same problem. I don't remember it happening on en_US when I first installed Wok but then I noticed it started not displaying certain tabs on Wok. Tried going back to en_US and it does the same thing now.

**Comment by alinefm** [comment]
Just one more information, have you verified that on which OS? And on latest Chrome and Firefox?

**Comment by alinefm** [comment]
I could reproduce it now. I will work on a patch to fix it.
Thank you all for the help.

**Comment by JoseGoncalves** [comment]
This problem still occurs for me in a fresh install over a Debian 8.7 distro.

I have rebuild Wok (2.4.0-3.gitf5aa7e8) and Gingerbase (2.3.0-rc1.6.giteccc7a6) and install it on my machine. When accessing Wok with language/locale set to English (US) in the browser I don't see nothing in the Wok tab, and /var/log/wok/wok-error.log reports:

```
*** Ginger Base: Running capabilities tests ***
System Report Tool ...: True
Logging AptUpdate features.
System Update Tool ...: True
Repo Management Tool .: deb
*** Ginger Base: Capabilities tests completed ***
[05/Apr/2017:10:17:52] ENGINE Listening for SIGHUP.
[05/Apr/2017:10:17:52] ENGINE Listening for SIGTERM.
[05/Apr/2017:10:17:52] ENGINE Listening for SIGUSR1.
[05/Apr/2017:10:17:52] ENGINE Bus STARTING
[05/Apr/2017:10:17:52] ENGINE Serving on http://127.0.0.1:8010
[05/Apr/2017:10:17:52] ENGINE Bus STARTED
[05/Apr/2017:10:19:38] ENGINE Started monitor thread 'Session cleanup'.
[05/Apr/2017:10:20:06] HTTP Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/wok/root.py", line 129, in tabs
    context = template.render('/tabs/' + page, data)
  File "/usr/lib/python2.7/dist-packages/wok/template.py", line 128, in render
    return render_cheetah_file(resource, data)
  File "/usr/lib/python2.7/dist-packages/wok/template.py", line 103, in render_cheetah_file
    return Template(file=filename, searchList=params).respond()
  File "_usr_share_wok_ui_pages_tabs_user_log_html_tmpl.py", line 106, in respond
  File "/usr/lib/python2.7/gettext.py", line 469, in translation
    raise IOError(ENOENT, 'No translation file found for domain', domain)
IOError: [Errno 2] No translation file found for domain: 'wok'
```

**Comment by alinefm** [comment]
Hi @JoseGoncalves 

I could only reproduce the problem when setting the default browser language to en_GB.
For en_US there is a domain file for wok as you can check as below:

```
ls /usr/share/locale/en_US/LC_MESSAGES
```

I don't know how you have rebuilt the packages but I could not find any commit as 5aa7e8 (2.4.0-3.gitf5aa7e8) as Wok tree.

The right commit is https://github.com/kimchi-project/wok/commit/4dbab0b0273449886c0fbb686c5670d57a67912d and it should generate a package like wok-2.4.0-2.git4dbab0b

**Comment by JoseGoncalves** [comment]
Hi @alinefm 

I've rebuild from Wok's from master branch. In there the latest commit is f5aa7e8.
The build process was:

```
$ git clone https://github.com/kimchi-project/wok
$ cd wok
$ git checkout master
$ ./autogen.sh --system
$ make
$ fakeroot make deb
```

The deb package has inside the "mo" files:
```
$ dpkg -c wok-2.4.0-3.gitf5aa7e8.noarch.deb | grep "\.mo"
-rw-r--r-- root/root      6613 2017-04-05 09:56 ./usr/share/locale/zh_TW/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      3038 2017-04-05 09:56 ./usr/share/locale/ru_RU/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      2805 2017-04-05 09:56 ./usr/share/locale/ko_KR/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      7844 2017-04-05 09:56 ./usr/share/locale/ja_JP/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      2697 2017-04-05 09:56 ./usr/share/locale/it_IT/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      3082 2017-04-05 09:56 ./usr/share/locale/fr_FR/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      2728 2017-04-05 09:56 ./usr/share/locale/es_ES/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      2701 2017-04-05 09:56 ./usr/share/locale/de_DE/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      6629 2017-04-05 09:56 ./usr/share/locale/zh_CN/LC_MESSAGES/wok.mo
-rw-r--r-- root/root      3672 2017-04-05 09:56 ./usr/share/locale/pt_BR/LC_MESSAGES/wok.mo
-rw-r--r-- root/root       457 2017-04-05 09:56 ./usr/share/locale/en_US/LC_MESSAGES/wok.mo
```
but after I install the package I don't see the file installed:

```
$ sudo dpkg -i wok-2.4.0-3.gitf5aa7e8.noarch.deb 
(Reading database ... 31589 files and directories currently installed.)
Preparing to unpack wok-2.4.0-3.gitf5aa7e8.noarch.deb ...
Unpacking wok (2.4.0) over (2.4.0) ...
Setting up wok (2.4.0) ...
Processing triggers for man-db (2.7.0.2-5) ...
$ find /usr/share/locale -name "wok.mo"
$
```

Weird!

**Comment by alinefm** [comment]
Hi @JoseGoncalves 

What is the output of:

```
ls /usr/share/locale/en_US/LC_MESSAGES
```
?

**Comment by JoseGoncalves** [comment]
Hi @alinefm 

Found the problem! I had the 'localepurge' package installed on my Debian VM and that was cleaning the installation of all the locales whenever a new package was installed.
After removing that package, I have no errors and the everything displays OK.

Nevertheless, if I select other language (I've tested Spanish and Portuguese) I always see the Wok interface in English (and the log is without errors). Any idea on what could be the problem now?

**Comment by alinefm** [comment]
Hi @JoseGoncalves 

Glad to know it is working now!

About what you asked, Wok does not have full support for all languages.
You can check that at https://github.com/kimchi-project/wok/blob/master/po/pt_BR.po which does not have all messages translated. Because that, you continue to see some words in English (which is the default fallback)

**Comment by JoseGoncalves** [comment]
@alinefm the problem that I'm experiencing is that I don't see anything translated! For instance "Help", "About" and "Log out" appear as before when I select pt_BR, when they should appear "Ajuda", "Sobre" and "Sair".

**Comment by alinefm** [comment]
Weird! I will check that later this week. Thanks for reporting.

**Comment by JoseGoncalves** [comment]
Just to confirm that this was not a problem in my debian package building, I've rebuild in the same way the version from git tag 2.4.0, which generated a package named wok-2.4.0-0.noarch.deb, and installing this I see the translated expressions.
Only when I build with the latest sources from the master branch, which generates a package named wok-2.4.0-3.gitf5aa7e8.noarch.deb, the translation fails.

**Comment by alinefm** [comment]
@JoseGoncalves I've just committed a patch that may be fix the problem you mentioned.

**Comment by JoseGoncalves** [comment]
@alinefm I confirm that your patch solved the translation problem. Thanks!

**Comment by spaceheadx** [comment]
@alinefm Thanks a lot for the fixes! is there a chance you will release RPMs/packages in next couple of days that include the recent changes?
Or is there any documented way to do this on my own?

**Comment by JoseGoncalves** [comment]
@spaceheadx Did not try it, but you should be able to build an RPM package from the latest sources with:

```
$ git clone https://github.com/kimchi-project/wok
$ cd wok
$ ./autogen.sh --system
$ make
$ make rpm
```

**Comment by alinefm** [comment]
@spaceheadx I don't think in release official packages with those fixes soon, but you can do it by yourself.
What @JoseGoncalves said is correct. For deb packages, run 

```
make deb
```

The commands are the same for Kimchi and Ginger Base as well.

**Comment by JoseGoncalves** [comment]
@alinefm This information should be supplied in the README.md files, don't you think?

**Comment by spaceheadx** [comment]
@JoseGoncalves @alinefm Thanks to both of you, I can confirm it works. I build RPMs for all the kimchi-project components and ran them sucessfully on CentOS. +1 for adding this to README.

**Comment by JoseGoncalves** [comment]
@alinefm Just a note. When building deb packages, and if you are building from a non root user, you should issue the following command:

```
$ fakeroot make deb
```
because without prefixing *fakeroot* the files inside the package will be with the user and group id from the user you are building the package.

**Comment by aaronmailageek** [comment]
#219 - I used this as the work around on Fedora && Centos
