### ISSUE TITLE
Wok wont start correctly after reboot

### ISSUE THREAD

**Issue by tomaae** [kimchi-project/wok#195]
I have new install and wok wont start correctly after reboot. 
It looks like wok will start duplicate nginx instance during boot which cannot be controlled by service command. Also it will keep overwriting nginx site config on every start which cannot be disabled from what I can tell.

`# dpkg -l|grep -E "wok|kimchi|ginger"`
ii  ginger                               2.3.1                                 all          Ginger plug-in for Wok - Webserver Originated from Kimchi
ii  ginger-base                          2.2.2                                 all          Ginger Base is an open source base host management plugin for Wok (Webserver Originated from Kimchi), that provides an intuitive web panel with common tools for configuring and managing the Linux systems.
ii  kimchi                               2.3.1                                 all          Kimchi web application
ii  wok                                  2.3.1                                 all          Wok - Webserver Originated from Kimchi

### After boot state:
syslog:
Dec 21 08:58:36 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Dec 21 08:58:36 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Dec 21 08:58:36 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
Dec 21 08:58:36 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Dec 21 08:58:36 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Dec 21 08:58:36 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Dec 21 08:58:36 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
Dec 21 08:58:36 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Dec 21 08:58:37 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Dec 21 08:58:37 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Dec 21 08:58:37 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
Dec 21 08:58:37 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Dec 21 08:58:37 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Dec 21 08:58:37 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Dec 21 08:58:37 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
Dec 21 08:58:37 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Dec 21 08:58:38 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
Dec 21 08:58:38 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
Dec 21 08:58:38 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8001 failed (98: Address already in use)
Dec 21 08:58:38 hikari nginx[1622]: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
Dec 21 08:58:38 hikari nginx[1622]: nginx: [emerg] still could not bind()
Dec 21 08:58:38 hikari systemd[1]: nginx.service: control process exited, code=exited status=1
Dec 21 08:58:38 hikari systemd[1]: Failed to start LSB: Stop/start nginx.
Dec 21 08:58:38 hikari systemd[1]: Unit nginx.service entered failed state.
Dec 21 08:58:38 hikari wokd[1236]: WOKPROXY0001E: WOKPROXY0001E
Dec 21 08:58:38 hikari systemd[1]: Starting Multi-User System.
Dec 21 08:58:38 hikari systemd[1]: Reached target Multi-User System.
Dec 21 08:58:38 hikari systemd[1]: Starting Graphical Interface.
Dec 21 08:58:38 hikari systemd[1]: Reached target Graphical Interface.
Dec 21 08:58:38 hikari systemd[1]: Starting Update UTMP about System Runlevel Changes...
Dec 21 08:58:38 hikari wokd[1236]: Traceback (most recent call last):
Dec 21 08:58:38 hikari wokd[1236]: File "/usr/bin/wokd", line 106, in <module>
Dec 21 08:58:38 hikari wokd[1236]: sys.exit(main(sys.argv[1:]))
Dec 21 08:58:38 hikari wokd[1236]: File "/usr/bin/wokd", line 103, in main
Dec 21 08:58:38 hikari wokd[1236]: wok.server.main(options)
Dec 21 08:58:38 hikari wokd[1236]: File "/usr/lib/python2.7/dist-packages/wok/server.py", line 220, in main
Dec 21 08:58:38 hikari wokd[1236]: srv = Server(options)
Dec 21 08:58:38 hikari wokd[1236]: File "/usr/lib/python2.7/dist-packages/wok/server.py", line 65, in __init__
Dec 21 08:58:38 hikari wokd[1236]: start_proxy(options)
Dec 21 08:58:38 hikari wokd[1236]: File "/usr/lib/python2.7/dist-packages/wok/proxy.py", line 136, in start_proxy
Dec 21 08:58:38 hikari wokd[1236]: raise OperationFailed('WOKPROXY0001E', {'error': error})
Dec 21 08:58:38 hikari wokd[1236]: wok.exception.OperationFailed: WOKPROXY0001E: WOKPROXY0001E

### Processes:
`# wokd --environment=dev`
WOKPROXY0001E: WOKPROXY0001E
Traceback (most recent call last):
  File "/usr/bin/wokd", line 106, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/wokd", line 103, in main
    wok.server.main(options)
  File "/usr/lib/python2.7/dist-packages/wok/server.py", line 220, in main
    srv = Server(options)
  File "/usr/lib/python2.7/dist-packages/wok/server.py", line 65, in __init__
    start_proxy(options)
  File "/usr/lib/python2.7/dist-packages/wok/proxy.py", line 136, in start_proxy
    raise OperationFailed('WOKPROXY0001E', {'error': error})
wok.exception.OperationFailed: WOKPROXY0001E: WOKPROXY0001E
`# psg wok`
root      3425  1743  0 09:03 pts/0    00:00:00 grep -i wok
`# service nginx stop`
`# psg nginx`
root      1662     1  0 08:58 ?        00:00:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
www-data  1663  1662  0 08:58 ?        00:00:00 nginx: worker process
www-data  1664  1662  0 08:58 ?        00:00:00 nginx: worker process
root      2854  1743  0 09:01 pts/0    00:00:00 grep -i nginx

### Manual fix after boot ("service nginx stop" wont work, so have to kill nginx processes):
`# killall nginx`
`# psg nginx`
root      2881  1743  0 09:01 pts/0    00:00:00 grep -i nginx
`# service wokd start`
`# service nginx start`
`# psg wok`
root      3517     1 53 09:03 ?        00:00:04 python2 /usr/bin/wokd
root      3938  3517  0 09:03 ?        00:00:00 python2 /usr/bin/wokd
root      3957  1743  0 09:03 pts/0    00:00:00 grep -i wok
`# psg nginx`
root      3536     1  0 09:03 ?        00:00:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
www-data  3537  3536  0 09:03 ?        00:00:00 nginx: worker process
www-data  3538  3536  0 09:03 ?        00:00:00 nginx: worker process
root      3961  1743  0 09:03 pts/0    00:00:00 grep -i nginx

At this point everything works correctly until next reboot.

**Comment by alinefm** [comment]
Hi @shii1 

Did you do a fresh Wok 2.3.1 install? Or did you get it from an update process?
I am asking that, because on 2.3.1 version, Wok is installing the nginx configuration file under /etc/nginx/conf.d/wok.conf and from your logs your system is getting it from a different place

```
# psg nginx
root 3536 1 0 09:03 ? 00:00:00 nginx: master process /usr/sbin/nginx -c /etc/nginx/nginx.conf
www-data 3537 3536 0 09:03 ? 00:00:00 nginx: worker process
www-data 3538 3536 0 09:03 ? 00:00:00 nginx: worker process
root 3961 1743 0 09:03 pts/0 00:00:00 grep -i nginx
```

Also which OS are you testing it?

**Comment by shii1** [comment]
Hi @alinefm 

I had previous version installed before, but I uninstalled it, purged and manually deleted everything related from fs.
It did written its site config under /etc/nginx/conf.d/wok.conf. If you mean /etc/nginx/nginx.conf, thats main nginx config file, not site config.
I'm testing it under Debian 8
