### ISSUE TITLE
Support nginx server_name

### ISSUE THREAD

**Issue by nicko170** [kimchi-project/wok#197]
Hello, It would be good to be able to set nginx server_name, so we can run this as a block on a subdomain if needed.

I would expect this in /etc/wok/wok.conf - like the ssl_certificate.

I've set manually - but every server restart it's losing the config line.

**Comment by alinefm** [comment]
Hi @nicko170 

Wok is not regenerating the nginx config anymore. So you should be able to change the Wok nginx conf file as you want.

Please, the latest version of Wok, ie, 2.3.1
