### ISSUE TITLE
Plugins management - frontend

### ISSUE THREAD

**Issue by danielhb** [kimchi-project/wok#200]
We need an UI for the new backend implemented at #22 .

The APIs created there was:

/config/reload - reloads WoK
/config/plugins - get all the plug-ins (even the disabled ones)
/config/plugins/*name*/enable - enable a plug-in
/config/plugins/*name*/disable - disable a plug-in

Assigning at this moment to @biancafc but this can be subject to change anytime.

**Comment by danielhb** [comment]
The backend for this feature is now available. We can start developing the UI for it.

This is the API we're going to use for the first version of this UI:

/config/plugins - get all the plug-ins (even the disabled ones)
/config/plugins/name/enable - enable a plug-in
/config/plugins/name/disable - disable a plug-in

Note that the enable|disable actions updates not only the config files but also makes on the fly changes in WoK. 

I suggest a simple UI listing all available plug-ins with their state enabled ou disabled. Changing a plug-in state will immediately fire the equivalent enable|disable API (a warning message is a good idea when disabling the plug-in). After the operation is completed, we would need to reload the view to get the current plug-ins state again because, depending on the dependencies, a disable/enable action can disable/enable other plug-ins as well.

**Comment by alinefm** [comment]
Fixed by 32c9d0bae31271a6c107a85f8620cfdfa226ff81
