### ISSUE TITLE
Plugins image not showing

### ISSUE THREAD

**Issue by biancafc** [kimchi-project/wok#213]
Tested on CentOS:

<img width="1180" alt="screen shot 2017-03-20 at 12 04 45" src="https://cloud.githubusercontent.com/assets/6681745/24106027/84860f76-0d65-11e7-8967-efa50bee9ee2.png">

**Comment by alinefm** [comment]
Hi @biancafc 

I've just tested it on CentOS 7 and it is working as expected to me:

![screenshot from 2017-03-21 14-30-16](https://cloud.githubusercontent.com/assets/4921718/24161379/fe2e8e38-0e42-11e7-8c69-3b1a9f3162ac.png)

**Comment by alinefm** [comment]
Maybe something wrong on your setup or a slow connection. I will close this issue by now but feel free to reopen if the problem persists to you.

**Comment by DP19** [comment]
I am having this same issue as well, but the strange thing is I setup a second KVM server running wok and it is displaying the images correctly. Both on the same version of CentOS. If i follow the image link and open it in a new tab it displays correctly 

![screen shot 2017-05-11 at 10 19 23 am](https://cloud.githubusercontent.com/assets/20734057/25954226/96e75b60-3633-11e7-9eca-c93925116dc0.png)
![screen shot 2017-05-11 at 10 19 32 am](https://cloud.githubusercontent.com/assets/20734057/25954229/980baa6e-3633-11e7-8594-23edbe9d03cd.png)
<img width="634" alt="screen shot 2017-05-11 at 10 19 39 am" src="https://cloud.githubusercontent.com/assets/20734057/25954232/992693a0-3633-11e7-8490-173923cd9349.png">
