### ISSUE TITLE
wok runs on localhost:8010 only how to fix this?

### ISSUE THREAD

**Issue by gzcwnk** [kimchi-project/wok#225]
I seem to have wok running but it only runs on http://localhost:8010, nothing is on 8001.

I attempted to put host = 0.0.0.0 into /etc/wok/wok.conf and did a restart but nothing changed still cant connect on the external IP.

How to fix this please?

**Comment by alinefm** [comment]
Do you have firewall and selinux properly configured? https://github.com/kimchi-project/wok/blob/master/docs/troubleshooting.md

**Comment by gzcwnk** [comment]
Hi,  port 8001 actually became active/available some minutes after booting.  

In any event  while wok works, kimchi wont install as it cant find libvirt-bin.   I would think the deb package is simply incorrect.  I also tried a force install, still no go. I assume that no one really is used to deb distros but rpms distros but I compiled from tar.gz and still not go so Ive given up.

No matter I've switched to a project called cockpit, backported to debian9, installed and works fine. 

In terms of troubleshooting, Ive opened another thread with some simple suggestions to improve which it desperately needs.

**Comment by gzcwnk** [comment]
PS no firewall and no selinux, this isnt RHEL or Centos but Debian.  I think you need to find someone who can put deb's together properly.

**Comment by alinefm** [comment]
Cockpit is for host management. So I guess you would want to install Ginger instead of Kimchi.

Anyway, just to let you know, no one in Wok community is testing it over Debian. So probably that is the reason it does not work for you. But, we validated it on Ubuntu and it works fine.

**Comment by gzcwnk** [comment]
Actually Cockpit does VMs (KVM) and Docker containers as well.   I could pretty much figure out on one is doing Debian in wok. though if it installs on Ubuntu it should install on Debian, this would be (is) the first package I've ever met that didnt.
