### ISSUE TITLE
can not login in on fedora27 

### ISSUE THREAD

**Issue by elkmil** [kimchi-project/wok#240]
kimchi can't login in on fedora27 and fedora 28 system
kimchi and wok were build from master branch  
kimchi   2.5.0-23.git40de9894.fc27    
 wok     2.5.0-28.git8389ccd6.fc27 

sudo systemctl restart wokd

I can't login in with my system user
WOKAUTH0008E: The username or password you entered is incorrect. Please try again

**Comment by thenets** [comment]
I had exactly same problem with CentOS 7. So I just give up and use the Ubuntu 18.04 and I had other problems too but was solved if I install `nginx` before install `kimchi` and `wok`.

**Comment by piotr-gbyliczek** [comment]
Have a look at :

https://github.com/kimchi-project/kimchi/issues/1232

Regards,
Piotr

**Comment by alinefm** [comment]
Closing this ticket as duplicated of kimchi-project/kimchi#1232
