### ISSUE TITLE
attach new disk size unit error

### ISSUE THREAD

**Issue by morecool** [kimchi-project/wok#252]
![image](https://user-images.githubusercontent.com/9711761/46593134-66372d80-cb04-11e8-8544-3c72befa61d7.png)

disk size unit guided GB

but it's work KB. 
plz check this.

**Comment by alinefm** [comment]
Thanks for reporting! I will check it again but I thought it was already fixed. Which Kimchi version you using?

**Comment by alinefm** [comment]
Fixed by 832a2d3c26
