### ISSUE TITLE
no license in  kimchi  project 

### ISSUE THREAD

**Issue by eliyahu77** [kimchi-project/wok#253]
cannot found license in this project , all the project is open source ?

**Comment by duper51** [comment]
I believe the license is in all of the source files themselves, I've noticed it on occasion if you'd like to look!

**Comment by alinefm** [comment]
The licenses are available at the source code main level:

For wok, please, check:

https://github.com/kimchi-project/wok/blob/master/COPYING
https://github.com/kimchi-project/wok/blob/master/COPYING.ASL2
https://github.com/kimchi-project/wok/blob/master/COPYING.LGPL

For Kimchi:

https://github.com/kimchi-project/kimchi/blob/master/COPYING
https://github.com/kimchi-project/kimchi/blob/master/COPYING.ASL2
https://github.com/kimchi-project/kimchi/blob/master/COPYING.LGPL
