### ISSUE TITLE
Change localhost access only behavior

### ISSUE THREAD

**Issue by t0k4rt** [kimchi-project/wok#259]
Hello, 
I'm working in an environment where it could be very usefull to get access to Kimchi from other ip than 127.0.0.1.
is it possible to add an option to allow 0.0.0.0 access top kimchi ?
Would a PR would be accepted or appreciated to deal with that ?
thanks !
```
cherrypy.server.socket_host = '127.0.0.1'
```

**Comment by alinefm** [comment]
Hi @t0k4rt!

You should be able to access Kimchi using the real IP instead of 127.0.0.1. Maybe your nginx configuration is missing something. Could you check how is that? And if it looks like https://github.com/kimchi-project/wok/blob/master/src/nginx/wok.conf

**Comment by t0k4rt** [comment]
thanks for your answer, I'll check that !

**Comment by t0k4rt** [comment]
thanks for your answer, I'll check that !
