### ISSUE TITLE
[Feature request] Compress Wok logs

### ISSUE THREAD

**Issue by guilhermepiccoli** [kimchi-project/wok#26]
Hello, I want to suggest the gzip compression of kimchi logs. I noticed the logs present in /var/log/kimchi can become very large, so the gzip compression seems good idea.

Thanks, 

Guilherme

**Comment by alinefm** [comment]
It would be good to add logrotate too.

**Comment by alinefm** [comment]
Fixed by 83d3585eb9942fe6737727fa54f5c8428acf6335
