### ISSUE TITLE
Unable to import package 

### ISSUE THREAD

**Issue by hmhtb** [kimchi-project/wok#266]
I'm using anaconda environment and I am unable to import packages because of this error? any clue?
"not authorized `package name' @ error/constitute.c/WriteImage/1028.

Ubuntu16.04
GPU2070 RTX

**Comment by alinefm** [comment]
Hey @hmhtb !

I have never seen that before but I am not familiar with anaconda environment either so I don't think how much I can help on it.

**Comment by hmhtb** [comment]
> Hey @hmhtb !
> 
> I have never seen that before but I am not familiar with anaconda environment either so I don't think how much I can help on it.

Thanks for the response, The problem solved, I did not import python before importing the package.
#
import python
import tensorflow as tf

**Comment by alinefm** [comment]
I am glad to know it is working! I will close this issue then.
