### ISSUE TITLE
Build and Run-time dependencies for firewalld for fedora, RHEL and Ubuntu

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/wok#27]
Build and Run-time dependencies for firewalld for fedora, RHEL and Ubuntu
wok/Makefile.am has clear dependency of firewalld folder's for the targets : install-deb, install-data-local and uninstall-local .

Can we make firewalld as both build and runtime dependency for the applicable dirstros?

**Comment by alinefm** [comment]
Hi @chandrureddy 

A build dependency is when something is needed to build a package.
I understand firewalld is only a runtime dependency.

**Comment by alinefm** [comment]
Hi @chandrureddy !

I checked the code and identified you are right!
firewalld is also a build dependency as it is used for checking on Makefile.am.

```
    if test -d /usr/lib/firewalld/services/; then \                             
        mkdir -p $(DESTDIR)/usr/lib/firewalld/services/; \                      
        $(INSTALL_DATA) src/firewalld.xml $(DESTDIR)/usr/lib/firewalld/services/wokd.xml; \
    fi; \
```

Which may leads issues with the build system does not have it installed.

Are you going to send a patch for it?
