### ISSUE TITLE
Tab order in Host is not consistent

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/wok#28]
Order of tabs in host is not consistent..
example 1:
![screenshot from 2016-01-19 15 45 39](https://cloud.githubusercontent.com/assets/12499230/12444551/9c1bcad8-bf85-11e5-897f-e408b3598aa7.png)

example 2:
![screenshot from 2016-01-20 14 51 32](https://cloud.githubusercontent.com/assets/12499230/12444573/b17cb9dc-bf85-11e5-87b2-bc176aa449e0.png)

ideal order of the tabs would be "Dashboard", "Updates", "Administration", "Network", "Storage" as per design discussions when gingerbase plugin was formed.

**Comment by sureshab** [comment]
i guess this depends on the plugins order returned by /plugins api..
for the "example 1" machine the /plugins api output is 
[root@zfwcec106 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins'
[
  "gingerbase",
  "ginger",
  "gingers390x"
][root@zfwcec106 ~]#

for the "example 2" machine:
[suresh@localhost kimchi]$ curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://localhost:8001/plugins'
Enter host password for user 'root':
[
  "ginger",
  "gingerbase",
  "kimchi"
]

if /plugins  can return the order [gingerbase, ginger, gingers390x, kimchi] always depending on the installed plugins, could maintain the consistency in tab order in UI.
Gingerbase should be before ginger and gingers390x(if installed) should be after ginger 
i am not 100% sure,,but this might fix the issue

**Comment by atreyeemukhopadhyay** [comment]
As per the agreement we had for "[RFC] Porposal of grouping host management functionalities in UI menue tabs", ideal ordering of tabs in host should be "Dashboard", "Network", "Storage","Updates", "Administration".

Dashboard
      - System Statistics
      - System Information
Network
      - Interfaces
      - Open vSwitch
Storage
      - Volumes
      - Groups
      - Filesystems (local and remote)
      - SAN Adapters
      - Tape Devices (if arch=s390x)
      - Swap
Power (may not be active on all arch)
      - Settings
      - Sensors Monitor
Updates
      - Software Updates
      - Repositories
      - Firmware Updates (if arch=ppc64)
Administration
      - User Management
      - Debug Reports
      - Configuration Backup
      - SEP Configuration (if arch=ppc64)

**Comment by alinefm** [comment]
fixed by f34f3af56be0ef3b8e1319b7142c858664dfd140
