### ISSUE TITLE
HOST Tab not shown in Wok 3.0

### ISSUE THREAD

**Issue by maddis4free** [kimchi-project/wok#291]
I installed Wok/Kimchi 3.0 several times on a debian 10.

Wok & Virtualization tabs are shown as expected, but "Host" is missing. :(

![screenshot](https://user-images.githubusercontent.com/30572357/72209834-3c14ae00-34b3-11ea-88b4-108ff6ba1704.JPG)

**Comment by maddis4free** [comment]
sorry, its my fault and no bug...

**Comment by apolenary** [comment]
Hello,
>>>sorry, its my fault
maddis4free, What is the issue?
I have the same issue on debian 10. There are Wok & Virtualization tabs but there is not Host tab.

**Comment by Chewbaka69** [comment]
Same on debian 10....

**Comment by maddis4free** [comment]
i think, the missing host-tab is caused by a missing gingerbase-3.0 plugin.

ergo: no plugin -> no tab
