### ISSUE TITLE
Can't get wok to work with kimchi in Ubuntu 20.04

### ISSUE THREAD

**Issue by davystrong** [kimchi-project/wok#299]
Hi,
I tried to install wok/kimchi in Ubuntu 20.04, however it fails to read the default config with the error ```Failed to load plugin conf from /home/<user>/Downloads/wok/src/wok/plugins/kimchi/kimchi.conf: ("Config error in section: 'wok', option: 'enable', value: 'True'. Config values must be valid Python.", 'TypeError', ("unrepr does not recognize 'Constant'",))```
I don't understand the error, as the values of True and False are perfectly valid Python 3 and running the file in Python (removing the section titles) works perfectly. I also tried changing the values to 1 and 0, with no change.

**Comment by davystrong** [comment]
This seems to be an issue with the cherrypy unrepr function. According to the [the docs](https://docs.python.org/3/library/ast.html), AST now returns AST.Constant for all types in Python 3.8, and I believe this is causing the problem.
Should I close this issue, since it's not specifically a problem with wok?

**Comment by murugeshg** [comment]
I there any work around for this issue?

**Comment by davystrong** [comment]
I managed to get Kimchi (and therefore get around this issue) working by doing [this](https://github.com/kimchi-project/kimchi/issues/1318#issuecomment-610583198). Hope this helps

**Comment by murugeshg** [comment]
Hi davystrong, your work around resolved the error.

**Comment by murugeshg** [comment]
Thank you

**Comment by NZLostboy** [comment]
> I managed to get Kimchi (and therefore get around this issue) working by doing [this](https://github.com/kimchi-project/kimchi/issues/1318#issuecomment-610583198). Hope this helps

Did you ever get NoVNC working? I am currently trying to trouble shoot it. I got Wok and Kimchi installed on Ubuntu 20 and everything seems to work except the NoVNC console

**Comment by davystrong** [comment]
Strangely noVNC was working initially, however it isn't any more. I don't have time to look at this at the moment but if you find a solution, I'd be interested.

**Comment by HendryLeo** [comment]
> This seems to be an issue with the cherrypy unrepr function. According to the [the docs](https://docs.python.org/3/library/ast.html), AST now returns AST.Constant for all types in Python 3.8, and I believe this is causing the problem.
> Should I close this issue, since it's not specifically a problem with wok?

my solution is to 

1. sudo apt-get remove python3-cherrypy3
2. sudo pip3 install cherrypy

**Comment by alinefm** [comment]
I' ve just pushed a fix for the cherrypy Parser issue. I will release a 3.0.1 version soon that will have fully Ubuntu 20.04 support

**Comment by Fuquan999** [comment]
Hi alinefm  + All,

May I ask is that version of 3.0.1 still in the making? If so would there be a possible public release date? And if that is still in the works would someone knowledgeable be able to follow it up with a Step-By-Step Ubuntu 20 tutorial (as the existing ones  are not straight forward and just do not seem to work problem free as there is even a video but the person [on detailed observation] ran into issues and off camera did a work around and fixed them "somehow") as that would be highly appreciated.

Kimchi in my view is one of the best out there for the community but simplicity/clarity of installation is what probably keeps many away from really putting it to good use.

Thanks and hope all is hanging in there is such questionable times.
Peace
Fuquan
