### ISSUE TITLE
kimchi on ubuntu 20 dependencies 

### ISSUE THREAD

**Issue by dongfanglong2012** [kimchi-project/wok#303]
I am trying to install kimchi on ubuntu 20 but i cant seem to figure out how to make the dependencies work. I'm guessing its a python2 python3 problem but I don't know how to fix it. 

used the commands from 
https://github.com/kimchi-project/wok/releases/tag/3.0.0

result 
`
bob@bob:~$ sudo apt install -y ./wok-3.0.0-0.ubuntu.noarch.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 ginger-base : Depends: python-apt but it is not installed
               Depends: python-cherrypy3 but it is not installable
               Depends: python-configobj but it is not installable
               Depends: python-lxml but it is not installed
               Depends: python-parted but it is not installable
               Depends: python-psutil (>= 0.6.0) but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
`
https://pastebin.com/cvNuE9t7 <-- retains the formatting for easier reading

apt --fix-broken install does not fix it

I looked at this post but am not sure how to do what is described
https://github.com/kimchi-project/kimchi/issues/1318#issuecomment-610583198

also i got the python-m2crypto to python3-m2crypto problem fixed using this site
https://forums.linuxmint.com/viewtopic.php?t=35136
and editing the dependency 

I am probably messing this whole process up bad and missing something but i have not found any help on google. every thing i find about setting up kimchi doesnt work do to dependencies. Does anyone know how to make this work?

**Comment by dongfanglong2012** [comment]
ok disregard im a dingus. i was running the install on the kimchi-2 not kimchi-3. I still dont have a virtualization tab but it is installed

**Comment by joaoguariglia** [comment]
## Ubuntu 20.04 On Raspberry 4 8GB ##
# wget http://ftp.us.debian.org/debian/pool/main/m/m2crypto/python-m2crypto_0.31.0-4_arm64.deb
# apt install gdebi nginx
# gdebi python-m2crypto_0.31.0-4_arm64.deb
https://github.com/kimchi-project/kimchi/releases/tag/3.0.0
# apt install -y ./wok-3.0.0-0.ubuntu.noarch.deb
# apt install -y python3-pip pkg-config libnl-route-3-dev
# wget https://raw.githubusercontent.com/kimchi-project/kimchi/master/requirements-UBUNTU.txt
# pip3 install -r requirements-UBUNTU.txt
# wget https://github.com/kimchi-project/kimchi/releases/download/3.0.0/kimchi-3.0.0-0.noarch.deb
# apt install -y ./kimchi-3.0.0-0.noarch.deb
# service wokd start
# service ufw stop
or
# iptables -A INPUT -p tcp --dport 8001 -j ACCEPT

But error:
N: Download is performed unsandboxed as root as file '/root/kimchi-3.0.0-0.noarch.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

**Comment by naamancampbell** [comment]
Thanks for logging issue - present on Ubuntu 20.10 and fixed with the `python-m2crypto` -> `python3-m2crypto` deb package fix.
https://github.com/kimchi-project/wok/issues/306#issuecomment-689894744 also required on Ubuntu 20.10
