### ISSUE TITLE
Changng the host = parm in /etc/wok/wok.conf doesn't restrict wok from listening on all network interfaces

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/wok#32]
We would like to restrict the wok to listen on only our private network interface,  and not public  interface.  

So we update the /etc/wok/wok.conf file like so:

[server]
host = private network interface IP

However,  after restarting wokd.service,   we still see the 
wok ports  (8000,  8002)  in netstat with 0.0.0.0 : 

tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN

and so,  we can still access HVM thru our public network.

#=== Steps to Reproduce ====================================
#===========================================================
1.  Update the wok.conf file to set host =  < a specific IP >
2.  Restart wokd.service
3.  Attempt to access the wok thru another IP interface - not the one
specified in the host =   parm

[root@zp93k6 wok]# cat /etc/system-release
KVM for IBM z Systems release 1.1.1 (Z)

**Comment by alinefm** [comment]
Fixed by a5a2390e3600dd2446b729f32ef9e7db3b943a2a
