### ISSUE TITLE
User Activity Log UI

### ISSUE THREAD

**Issue by samhenri** [kimchi-project/wok#36]
I'm compiling all the requirements for User Activity Log in the mailing list and adding it here.

Location:

- Will be displayed as a new tab in Wok navbar next to other plugins (Host, Virtualization, new tab).
- Title: **To be defined** (_Settings_? _Configuration_?)
- In order to add the new tab, we'll have to follow wok plugins structure and create a new folder in ```/src/wok/plugins/new-plugin/tab-ext.xml```
- Navbar color: Red / Old Administration new-ui color (previously associated with Ginger) **To be confirmed**
- "Plugin" name: same as the title

UI:
- Must follow Ginger and Gingerbase collapsible panels
- Tab title: User Activity Log
- Panel title: Logs
- Elements:
 - Advanced Search area:
   - Plugin - Selectpicker / Combobox - Only 1 option
    - User - Input Text (If there's an API to get all users then we can attach Typeahead.js to this field)
    - Request - Selectpicker / Combobox - Only 1 option
    - Date - From (**to be confirmed**) - Datepicker
    - Date - To (**to be confirmed**) - Datepicker
    - Button: Search (format JSON data to match selected fields)
    - Button: Reset to Default (clears search and restores JSON data to show only logs from current date)
 - Logs area:
   - jQuery Bootgrid Table
    - Show inline-search renamed to "Filter" - **To be confirmed**
    - Enable pagination
    - Hide dropdown buttons on the right (the one that filters records shown in page and the other one that filter columns)
    - Download button on top of the table. It will download the filtered JSON data from Advanced Search area and **not** the inline-search from jQuery Bootgrid
    - Add Bootstrap labels to plugins names (red for Wok, green for Kimchi, blue for Ginger and cyan to Gingerbase) - **To be confirmed**
    - Columns: Plugin, User, Request, Date

Wireframes (these were made with Google Chrome devtools, nevermind the "Edit Template" link)
![user-log-3](https://cloud.githubusercontent.com/assets/326107/13177244/f325fd68-d6fe-11e5-9f46-47dd05d5d8fa.png)
![user-log-4](https://cloud.githubusercontent.com/assets/326107/13177243/f32594ea-d6fe-11e5-9c3c-b6d854c8200b.png)

**Comment by samhenri** [comment]
The "Reset to Default" button would appear once the advanced search is applied.

**Comment by samhenri** [comment]
@alinefm @laggarcia can you confirm the "to be confirmed / defined" items? We need them confirmed in order to start developing this tab before code freeze

**Comment by samhenri** [comment]
@alinefm @laggarcia I'm ready to develop this task with static models (since the backend is not on the ML yet), I just need to confirm:
-Develop a new wok "plugin" with just the UI assets and Makefiles
OR
-Append a new static tab after wok genTabs() function is called and keep all user log assets (html pages, scss, css and js) with wok (wok-ui, login, wok scss and css files that are shared with kimchi, ginger and gingerbase)

Regarding the advanced search feature:
-Modal window
OR
-Collapsible panel

**Comment by alinefm** [comment]
Hi @samhenri 

For the new tab:
- The first tab level should be named as "Wok" (from the images above, replace "Configuration" to "Wok")
- The second tab level should be named as "Settings" (from the images above, replace "User log activity" to "Settings"
- I am OK with red color for this new tab

- For this first version, there will be no option to search for a range of dates.
It will only be possible for a specific date.

- OK for the inline filter

- The plugin color should be specified by the plugin instead of hard code it on wok.
I remember you have added a CSS class in the ta-ext.xml. Probably, we should go on thay way.

- Develop a new wok 'plugin' with Makefile and HTML files needed.

- Advanced search: the modal dialog you created looks good for me.

**Comment by alinefm** [comment]
Fixed by 0ac8635875dc6f7abf840ce821915366b548f021
