### ISSUE TITLE
make rpm on CentOS 7 fails

### ISSUE THREAD

**Issue by joukio** [kimchi-project/wok#39]
Running make rpm on CentOS 7 fails.

I downloaded the latest zip file from github.
Extracted it on a pristine CentOS installation.
Executed ./autogen.sh.
Executed make
Executed make rpm (failed with below error)
error: File not found: /root/wok-master/rpm/BUILDROOT/wok-2.0.0-0.el7.centos.x86_64/usr/lib/firewalld/services/wokd.xml

Line 130 in the specfile says: %{_prefix}/lib/firewalld/services/wokd.xml, but this isn't available. I guess the src/firewalld.xml file should be copied to that location, but that's just a wild guess.

regards

**Comment by joukio** [comment]
just made a small change in the wok.spec.fedora file. Add these lines:

%if 0%{?with_systemd}
# Install the upstart script
install -Dm 0640 src/firewalld.xml %{buildroot}/usr/lib/firewalld/services/wokd.xml
%endif


in the install section of the spec file and the compilation will give a RPM.

**Comment by alinefm** [comment]
Seems it was fixed for 2.3 release as there are packages available for CentOS 7 at http://kimchi-project.github.io/wok/downloads/
