### ISSUE TITLE
Upon log into WOK, getting error: WOKAUTH0002E: You are not authorized to access Kimchi

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/wok#40]
I have installed WOK , and plugins : gingerbase, ginger and gingers390x.
and from browser logged into wok.
I didnt see any issue on UI, but log says following -
tail -f /var/log/wok/wok-error.log 
[18/Mar/2016:12:43:01] ENGINE Bus STARTING
[18/Mar/2016:12:43:01] ENGINE Serving on 127.0.0.1:8010
**\* Running feature tests ***
**\* Feature tests completed ***
[18/Mar/2016:12:43:01] ENGINE Bus STARTED
[18/Mar/2016:12:43:25] ENGINE Started monitor thread 'Session cleanup'.
WOKAUTH0002E: You are not authorized to access Kimchi

**Comment by alinefm** [comment]
I noticed that when the session expired and I tried to do something on UI.
For example, login on Wok > Go to Virtualization tab > Storage tab

Wait some time to timeout the session, then try to list the storage volumes in a pool. Nothing will happen on UI and the error will be logged as you described (WOKAUTH0002E: You are not authorized to access Kimchi)

After refreshing the web page, I was redirected to Login page and everything started working fine again.

We need to refresh the page time by time to avoid displaying inconsistent data (due a multi user application) and redirect the user on session timeout.

**Comment by jay-katta** [comment]
I have seen this error immediately after installation on every login attempt. I didnt wait some time to timeout. I didnt install kimchi plugin.

**Comment by alinefm** [comment]
Hi @jay-katta 

Could you, so, provide step-by-step instructions to reproduce it?
Have you installed only wok and ginger? Is the issue persistent?

**Comment by jay-katta** [comment]
1. Install WOK
2. Install gingerbase, ginger
3. open url from browser - https://9.x.x.x:8001
4. Login page appears
5. When login page appears on browser, I see the error message in /var/log/wok/wok-error.log

It is persistent, with out entering userid and password, if I refresh the page, upon every refresh I see the same error line in wok-error.log

Tried login and logout,  when login prompt appears on browser , again I see the same error line in wok-error.log

**Comment by alinefm** [comment]
Hi @jay-katta 

Are  you able to see this issue? I am not able to reproduce it.

**Comment by pryorda** [comment]
I am able to reproduce this

```
[23/Aug/2016:15:41:17] ENGINE Listening for SIGHUP.
[23/Aug/2016:15:41:17] ENGINE Listening for SIGTERM.
[23/Aug/2016:15:41:17] ENGINE Listening for SIGUSR1.
[23/Aug/2016:15:41:17] ENGINE Bus STARTING
[23/Aug/2016:15:41:17] ENGINE Serving on http://127.0.0.1:8010
[23/Aug/2016:15:41:17] ENGINE Bus STARTED
[23/Aug/2016:15:41:51] ENGINE Started monitor thread 'Session cleanup'.
WOKAUTH0002E: You are not authorized to access Kimchi
WOKAUTH0002E: You are not authorized to access Kimchi
```

Dockerfile
```
FROM phusion/baseimage:latest
MAINTAINER Daniel Pryor <daniel@pryorda.net>

# Install Wok / GingerBase / KimChi

ENV PYTHONDONTWRITEBYTECODE=1
RUN export DEBIAN_FRONTEND=noninteractive && apt-get  update && \
    apt-get install -y gcc make autoconf automake gettext git pkgconf \
                       xsltproc logrotate python-cherrypy3 python-cheetah python-pam \
                       python-m2crypto python-jsonschema \
                       python-psutil python-ldap python-lxml nginx \
                       openssl fonts-font-awesome texlive-fonts-extra sudo \
                       python-apt sosreport python-configobj python-parted \
                       websockify novnc python-libvirt \
                       libvirt-bin nfs-common qemu-kvm python-parted \
                       python-ethtool sosreport python-ipaddr \
                       python-lxml open-iscsi python-guestfs \
                       libguestfs-tools spice-html5 python-magic \
                       python-paramiko pyflakes && \
    git clone --recursive https://github.com/kimchi-project/wok.git && cd wok && \
    git submodule update --remote && \
    ./build-all.sh && \
    ./autogen.sh --system && \
    make && make install && \
    #HACK BECAUSE KIMCHI IM NOT USING SYSTEMCTL
    sed -i --posix "s|cmd = \['system.*$|cmd = \['service', 'nginx', 'start'\]|g" /usr/lib/python2.7/dist-packages/wok/proxy.py && \
    cat /usr/lib/python2.7/dist-packages/wok/proxy.py

ADD 01_wokd.sh /etc/my_init.d/01_wokd.sh

# Cleaner
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Start Command
```
docker run -d -p "8001:8001" --restart=always --name wok-kimchi \
  -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro \
  -v /etc/shadow:/etc/shadow:ro \
  -v /home/storage/letsencrypt/live/pryorda.net/fullchain.pem:/etc/kimchi/kimchi-cert.pem:ro \
  -v /home/storage/letsencrypt/live/pryorda.net/privkey.pem:/etc/kimchi/kimchi-key.pem:ro \
  -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock \
  -v /var/lib/libvirt:/var/lib/libvirt \
  -v /etc/libvirt:/etc/libvirt \
  -v /freenas/lan/vm-storage/:/freenas/lan/vm-storage/ \
  kimchi
```

**Comment by alinefm** [comment]
I identified that is because when the UI is loaded, it tries to do some requests to server to get informatin to fill up the web page. But when the use has not logged in yet, the request will fail with 401 and the error message is displayed in the logs.

I will send a patch to remove the "Kimchi" name from the error message and get more details into it.
