### ISSUE TITLE
Modal dialog box not able to log user back in after timeout

### ISSUE THREAD

**Issue by harche** [kimchi-project/wok#58]
- Bring Up Kimchi 
- Goto Storage (or any other tab)
- Expand SAN Adapters (or any other section which has modal dialog box)
- Let window stay open and give it enough time for session to expire
- Click Add

You will get a small pop up window which looks just like a mini version of the login screen
Put in your id and credentials and enter. Browser displays
**405 Method Not Allowed**

**Comment by alinefm** [comment]
Hi @harche 

Could you attach a screenshot with the dialog you saw?

**Comment by harche** [comment]
https://imgur.com/a/CcuMe

**Comment by danielhb** [comment]
Hi @harche is this still happening?

**Comment by harche** [comment]
It's working fine now.
