### ISSUE TITLE
Jquery-bootgrid plugin library js is broken and showing js error 

### ISSUE THREAD

**Issue by atreyeemukhopadhyay** [kimchi-project/wok#8]
While page is loaded Jquery-bootgrid plugin library js file jquery.bootgrid.min.js is showing sysntax error.
As a result bootgrid components in ginger storage and networking tab are not working.

![jb issue](https://cloud.githubusercontent.com/assets/13199397/11818315/ba40d6b0-a37f-11e5-8f82-feee00d94dbb.png)

When the patch is applied using eml file the jquery.bootgrid.min.js  is broken. While wok-ui.html.tmpl loads the same, browser console shows the above error and bootgrid init function is showing undefined. 
Same is working for when patch is applied using .patch file .

**Comment by alinefm** [comment]
Fixed by 3fbdb61dd981db6b55ac3443f2b224f6a0bfe47e
