### ISSUE TITLE
ibvirt-bin.service failed to load

### ISSUE THREAD

**Issue by elproducto** [kimchi-project/wok#97]
I am attempting to utilize Kimchi, but running into issue starting Wokd service.  I get the following error when I attempt to start the Wokd service.  

**Wokd Start Error**
`Failed to start wokd.service: Unit libvirt-bin.service failed to load: No such file or directory.`

**Comment by pvital** [comment]
Hello @elproducto 

Could you tell us which distro and version are you using Wok, and also wok version?

Thanks.

**Comment by elproducto** [comment]
Distro is Debian Jessie.  I am not sure what version, but I download Ubuntu .deb package posted on the Kimchi project website.  Link to Deb file is Located at this URL https://kimchi-project.github.io/wok/downloads/

**Comment by pvital** [comment]
@elproducto I could reproduce your issue in a Debian Stable (jessie) release.

The thing is that Kimchi DEB package was developed to run in an Ubuntu system and the name of libvirt service in Ubuntu is different from the name in Fedora and Debian. 

To quickly solve your issue, please edit the _/etc/systemd/system/wokd.service.d/kimchi.conf_ and substitute the name **libvirt-bin** to **libvirtd**. Then, reload systems and restart wokd.

```
$ sudo vi /etc/systemd/system/wokd.service.d/kimchi.conf
<ESC>
:%s/libvirt-bin/libvirtd/g
:wq
$ sudo systemctl daemon-reload
$ sudo systemctl restart wok.service
```

**Comment by elproducto** [comment]
Pvital,

Thanks.  All is good now.
