### ISSUE TITLE
missing user activity log for gingers390x plug in

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/wok#99]
With the current implementation of user activity log, the actions performed with gingers390x plugin are not reported.

**Comment by alinefm** [comment]
The user log support needs to be add to the gingers390x plugin.
Each plugin is responsible to properly add the necessary configuration to Wok identify the logs.

**Comment by sureshab** [comment]
Opened issue - https://github.com/kimchi-project/gingers390x/issues/52 in gingers390x
